### ISSUE TITLE
Mapped URLs do not use their respective templates

### ISSUE THREAD

**Issue by sacr3dc0w** [bigcommerce/stencil-cli#1023]
### Expected behavior

Map a URL to a custom template and have it rendered using the correct template.

```
{
  "customLayouts": {
    "brand": {},
    "category": {},
    "page": {},
    "product": {
      "custom-signs-safety-signs.html": "/custom-totem-pole-rack-labels/"
    }
  }
}
```

<img width="2160" alt="what it should be" src="https://user-images.githubusercontent.com/5056945/200054309-f41c56de-7268-4278-ab16-c1ec17567544.png">

### Actual behavior

URL that's been mapped (a product in this instance) will revert to the default template for that page type. URLs mapped under product for custom templates use product.html, URLs mapped under page for custom templates use page.html, etc.

<img width="2160" alt="current" src="https://user-images.githubusercontent.com/5056945/200054292-709a2c12-a22a-4bf7-ab4c-88955e3ef40a.png">

### Steps to reproduce the behavior

Map a URL to a custom template, boot up stencil-cli, and visit that URL. What I did was just copy product.html into `custom/product` in the pages folder (create the folders if you don't have them) and give it the name for a custom template that matched what's in `customLayouts` object. Then I placed a string in that file, `Hello from custom-signs-safety-signs.html` and `Hello from product.html` in the default file to confirm the mapped template was not loading.

### Environment

Stencil-cli version `stencil --version`: 5.3.3

Node version `node -v`: v14.20.0

NPM version `npm -v`: 6.14.17

OS: Mac OS 12.6.1 (21G217)

**Comment by enkota** [comment]
Can confirm this is happening to custom pages now. Probably related to the recent fix for trailing slashes.
