### ISSUE TITLE
stencil push failed to upload new theme

### ISSUE THREAD

**Issue by czkiam** [bigcommerce/stencil-cli#1079]
### Expected behavior
Able to upload theme file using `stencil push` with stencil cli

### Actual behavior
faile to upload theme file using `stencil push` it return error
<img width="1408" alt="Screenshot at Mar 10 14-22-29" src="https://user-images.githubusercontent.com/19747140/224239328-af807b63-a4ac-44c1-afdb-e707263e6deb.png">
.
not ok -- JobCompletionStatusCheckError: Job Failed

A server error occurred

### Steps to reproduce behavior
run stencil push

### Environment

Stencil-cli version `stencil --version`:
4.1.0
Node version `node -v`:
v14.18.2
NPM version `npm -v`:
6.14.15
OS:
MacOS Monterey 12.6.1

**Comment by czkiam** [comment]
try to upload manually but theme file doesnt upload and show error. using different account has the same issue too.

**Comment by kulvirbadpixel** [comment]
I am also getting the same error. If someone finds a fix please let me know as well.

**Comment by jbogheand** [comment]
Same error, out of the blue

**Comment by celeweidmann** [comment]
Same error here.
> stencil --version
5.2.0
> node -v
v14.19.3
> npm -v
6.14.17
OS: Win 11

**Comment by mradilamin** [comment]
Same Error i am also facing. plz give me urgent solution

**Comment by nmalozzi** [comment]
Same issue. Started randomly yesterday. Did a `stencil push` successfully about 30min prior, and only made some minor CSS changes.

**Comment by spire-mike** [comment]
Same issue here. I also get an error when using `stencil bundle` and manually uploading the theme to the UI. The `bundle` command works, but the UI displays an error after upload:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/77629408/224362492-1edbe4d0-2e32-41cf-ba54-f19fd9dfc021.png">

**Comment by spire-mike** [comment]
I reached out to BigCommerce support and sen them the link to this thread. The rep said they would escalate the issue so somebody sees it quickly.

**Comment by thekanbo** [comment]
Our team had the same issues intermittently yesterday morning on a number of client stores, but by the afternoon, we were not able to upload any new themes to any store, either via the CLI or through the control panel.

**Comment by JoshuaMadrid-Demdaco** [comment]
Same thing here, glad to know it's not something i am doing wrong.

**Comment by bc-jcha** [comment]
Hi everyone, thank you for your patience. This issue has been fixed. You should be able to upload a theme now.

**Comment by nmalozzi** [comment]
Just confirmed that this is working again. Thanks!
