### ISSUE TITLE
Stencil Cli running stencil push returns error `not ok -- ThemeUploadError: Server Error`

### ISSUE THREAD

**Issue by joseph-vega12** [bigcommerce/stencil-cli#1144]
I am having an issue with pushing my changes  up using stencil push I am receiving an error `not ok -- ThemeUploadError: Server Error` right after "Zipping Files Finished is complete" , I just encountered this issue today I can confirm it is an issue with the Stencil Cli i tried reverting back to previous commits  on the changes to see where it might have broken but still the same issue.  I have also tried downloading the theme again directly from Bigcommerce storefront and trying running "stencil push" but i still get the same error. Everything was working fine just a couple of hours ago, thank you in advance for any help!

### Expected behavior

Stencil push should push any changes made on local to Bigcommerce storefront.

### Actual behavior

Stencil Push returns an error  `not ok -- ThemeUploadError: Server Error`.
<img width="1330" alt="Screenshot 2023-11-06 at 8 05 53 PM" src="https://github.com/bigcommerce/stencil-cli/assets/57374454/9ff237f0-618a-4f30-8708-2a2d012f8aed">

### Steps to reproduce behavior
Running `stencil push` will reproduce this error.

Stencil-cli version `stencil --version`: 6.1.1

Node version `node -v`:  14.20.0

NPM version `npm -v`:  6.14.17

OS: macOS

**Comment by joseph-vega12** [comment]
Any insight would be appreciated in resolving this error, error is not to clear already ready documentation but no such error

**Comment by njimenezmacloud** [comment]
We have the same issue, any idea will be appreciated

**Comment by joseph-vega12** [comment]
@njimenezmacloud was this working for you today then suddenly stopped working for you as well?

**Comment by Nyrih-EE** [comment]
Getting the same issue as well. I've also revert to pervious commits and tried to push, but still I get that error.

**Comment by njimenezmacloud** [comment]
Yes, exactly in the same way than you, I did the deploy in the morning and later I tried again with the same branch and it was not working.

**Comment by randolphpark** [comment]
Having same issue recently. Seems like issue that started to occur recently.

**Comment by LordDashMe** [comment]
Having same issue, this is working yesterday. Now it's showing this `not ok -- ThemeUploadError: Server Error`

Pipelines ❌ 
Local deployment ❌

**Comment by KashifWaheed980** [comment]
Having same issue 
not ok -- ThemeUploadError: Server Error

**Comment by dio5** [comment]
^

**Comment by jp06** [comment]
Should be fixed now? https://status.bigcommerce.com/incidents/8m0lnskbsy1p

**Comment by TomA-R** [comment]
hey folks, this should be fixed now - let us know if you still run into any issues
