### ISSUE TITLE
Could not fetch a list of the store channels: Request failed with status code 403

### ISSUE THREAD

**Issue by chmelev** [bigcommerce/stencil-cli#1185]
### Expected behavior
Theme gets applied without errors when doing the stencil push

### Actual behavior
Theme application step (after the "Would you like to apply your theme to your store?" question) fails with the following error:

`not ok -- Error: Could not fetch a list of the store channels: Request failed with status code 403`

### Steps to reproduce behavior
Get the **latest** (4/8/2024) stencil-cli, do the **stencil init**, and then **stencil push**.
NOTE - the pre-4/8/2024 version works fine

### Environment

Stencil-cli version `stencil --version`: 7.4.2

Node version `node -v`: 18.19.0

NPM version `npm -v`: 10.2.3

OS: fails on Windows and Linux

**Comment by AndrewBarber** [comment]
Initial look into this, I am thinking that the access token used, does not have access to `${apiHost}/stores/${storeHash}/v3/channels` endpoint. 

Looking into docs to see what permissions are required...

**Comment by AndrewBarber** [comment]
Ok looks highly likely this is permissions of the access token. Steps to recreate:

Goto: BCAdmin > Settings > Store-level API account > Create API Account 
Token type = Stencil CLI token

The token generated does not have access to `/v3/channels`. 

```
{
    "status": 403,
    "title": "You don't have a required scope to access the endpoint",
    "type": "https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes",
    "errors": {}
}
```

**Comment by chmelev** [comment]
How am I supposed to get the **Stencil CLI token** with ` /v3/channels` access? Is that an undocumented feature?

**Comment by AndrewBarber** [comment]
I'd expect that BC will need to fix this functionality when the token is generated from BC Admin.  

Two options to unblock you immediately would be:

- You could generate a V2/V3 token with the correct permissions. (I'm unable to check what those would be at the moment as I'm on mobile)
- Use a version of stencil cli prior to 7.4.2.

**Comment by tzvimoshe** [comment]
Following

**Comment by bc-jz** [comment]
Hi @chmelev,

Thank you for reporting this issue and sorry about the problem. I didn't recognize when adding this new "channels" request that the standard Stencil CLI token was missing the needed "read-only channel settings" permission. That became required with this change:
https://github.com/bigcommerce/stencil-cli/pull/1180

We have [released a new update, version 7.5.1,](https://github.com/bigcommerce/stencil-cli/releases/tag/7.5.1) that will address this issue for people running into the permission error. Please go ahead and update to the latest version of `stencil-cli` for a quick fix. Our change will simply bypass the permission error and make things act as they did before the update that introduced this new permission requirement (version 7.4.2).

Downgrading to version 7.4.1 or below is another way to resolve this issue quickly.

This new "channels" requirement is here to stay though so to accommodate that you will need to generate a new stencil cli auth token that includes the "read-only channel settings" permission (as suggested by @AndrewBarber).

That can be done within the control panel under `Settings` -> `Api` -> `Store-level Api Accounts` but you do need owner permissions to the store to do this. Right now when creating the new token you do need to add this new permission manually:
<img width="300" alt="Screenshot 2024-04-10 at 8 07 49 AM" src="https://github.com/bigcommerce/stencil-cli/assets/6527334/63d074e7-1ceb-4198-93f8-d6e6b7f56ca9">

We are also in the process of updating the standard "Stencil CLI" to include the "read-only channel settings" permission so soon regenerating that specific token will correct this issue as well: 
<img width="716" alt="Screenshot 2024-04-10 at 8 10 16 AM" src="https://github.com/bigcommerce/stencil-cli/assets/6527334/e9abfbcd-ea9a-497b-affa-d9f8cccb5f7e">

Feel free to let me know if you have questions about this. Sorry again about this oversight.

**Comment by chmelev** [comment]
Hi @bc-jz,

Just to be clear - while the Stencil CLI Token generation is being fixed, you're suggesting using the V2/V3 API Token instead, right?

**Comment by bc-jz** [comment]
> Hi @bc-jz,
> 
> Just to be clear - while the Stencil CLI Token generation is being fixed, you're suggesting using the V2/V3 API Token instead, right?

I am suggesting it as a possible workaround but if you don't want to bother with choosing the correct scopes then you can just wait for the stencil cli token update. That should be available in the next day and once you are on version 7.5.1+ there is no longer a blocking failure if your auth token is missing the "store channel settings read only" scope.

The "stencil CLI token" is simply a v2/v3 api token where we predefine the scopes it should have available based on the actions taken when utilizing `stencli-cli`. The necessary scopes you would apply to match what we will have on the stencil cli token are:

- store sites read only
- store information
- store channel settings read only

There is one more scope that changes depending on if you are only doing local development or needing to publish changes. If you need to publish changes then you need the `store_themes_manage` scope. That can be more conservatively set to `store_themes_read_only` if you are only doing local development.

The danger with generating a v2/v3 api token to replace the stencil cli token is simply that you offer too many or too few scopes. Too few can result in errors like we have seen with this missing Channels scope. Too many would grant whomever is using this token greater access to your store's api than what is necessary to do theme development.

**Comment by bc-jz** [comment]
To close the loop on this I confirmed that the Stencil CLI now has all needed scopes to work properly with the newest versions of `stencil-cli`. As a summary for anyone seeing 403 errors when using version 7.4.2 or 7.5.0 of `stencil-cli`:

1) You should regenerate your "Stencil CLI" token to get the scopes needed to avoid the error.
2) If you can't get a new token soon you can downgrade to 7.4.1 or update to 7.5.1+ to also get around the error.

**Comment by anemos474** [comment]
Hi everyone, I’m trying to generate a new token now, but here is the issue: when creating a new token for Stencil CLI, I don’t see the channel settings on my side.

<img width="1605" height="860" alt="Image" src="https://github.com/user-attachments/assets/791c00af-ed17-4681-91b7-1d4a5b3a195c" />

**Comment by bc-jz** [comment]
> Hi everyone, I’m trying to generate a new token now, but here is the issue: when creating a new token for Stencil CLI, I don’t see the channel settings on my side.
> 
> <img alt="Image" width="1605" height="860" src="https://private-user-images.githubusercontent.com/32639007/594558242-791c00af-ed17-4681-91b7-1d4a5b3a195c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzkyMTIwNjAsIm5iZiI6MTc3OTIxMTc2MCwicGF0aCI6Ii8zMjYzOTAwNy81OTQ1NTgyNDItNzkxYzAwYWYtZWQxNy00NjgxLTkxYjctMWQ0YTViM2ExOTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNTE5VDE3MjkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliY2MyN2U0ZGM5NTk5YmU2N2E0Njc4MDIwNzEwNmI1N2YyMjAyYjUxZTBhM2ZmOWNiYjkzYzQ0ZDkwMTZiMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.wW0sKrxD236Oe_tH9W-DT3l8Sd0I6VXViTh-j8G4-ls">

Hey @anemos474,

You should not expect to see any of the scope choices when you select "Stencil CLI token" as we have pre-selected all the scopes which apply in that case. Furthermore, we have added the Channel scope to that token so you should be good to go just generating it.

If you choose to create a "v2/v3" token then you will need to manually select the scopes you want applied to the token.

**Comment by anemos474** [comment]
Hi @bc-jz, thank you. 

I have already generated a new token, but I’m still getting a 403 error when trying to retrieve the channel ID.

That’s why I started investigating the reason and found this case. After checking its content, I saw that there should be a scope selection, which is currently missing in my version. That is why I assumed that the token issue might be caused by the missing scope.

At the moment, your response has confused me a bit, and the issue seems to be getting deeper :) If this is already built in, but my new token still does not work.

**Comment by bc-jz** [comment]
> Hi [@bc-jz](https://github.com/bc-jz), thank you.
> 
> I have already generated a new token, but I’m still getting a 403 error when trying to retrieve the channel ID.
> 
> That’s why I started investigating the reason and found this case. After checking its content, I saw that there should be a scope selection, which is currently missing in my version. That is why I assumed that the token issue might be caused by the missing scope.
> 
> At the moment, your response has confused me a bit, and the issue seems to be getting deeper :) If this is already built in, but my new token still does not work.

@anemos474 
The needed scope is built-in when you choose the "stencil CLI token".  Additionally we don't throw a hard failure anymore if the scope referenced in this thread is missing. Instead we eat that error and return an unfiltered list of stores.

Your 403 error must be coming from something else. There must be some other type of issue with the token being provided or with the store data.

What command are you running that results in this error? Can you provide a copy of the full error message you are seeing? What version of Stencil CLI are you running?
