### ISSUE TITLE
not ok -- StencilConfigReadError: Please run $ stencil init first.

### ISSUE THREAD

**Issue by ethansheffield** [bigcommerce/stencil-cli#1206]
This used to work flawlessly, then it would work sometimes and not others, now it doesn't work at all. I'm not sure what exactly is wrong here... any help is greatly appreciated.

### Expected behavior
Run stencil push -a -d -c 1
Validating theme...

### Actual behavior
Run stencil push -a -d -c 1
not ok -- StencilConfigReadError: Please run $ stencil init first.
Please visit the troubleshooting page https://developer.bigcommerce.com/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.
If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
Error: Process completed with exit code 1.

### Steps to reproduce behavior
merge and deploy using this deployment.yml

name: Deploy Theme to BigCommerce Store

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18.x'
      
      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Stencil CLI Dependency
        run: npm install -g @bigcommerce/stencil-cli

      - name: Install Dependencies
        run: npm ci

      - name: Connect to store
        env:
          URL: ${{ secrets.BIGCOMMERCE_STORE_URL }}
          TOKEN: ${{ secrets.BIGCOMMERCE_ACCESS_TOKEN }}
        run: stencil init -u $URL -t $TOKEN -p 3000 -h https://api.bigcommerce.com

      - name: Push theme live, automatically deleting oldest theme if necessary
        run: stencil push -a -d -c 1

### Environment

Stencil-cli version `stencil --version`:
7.5.5

Node version `node -v`:
v18.15.0

NPM version `npm -v`:
9.5.0

OS:
Sonoma 14.2

**Comment by jairo-bc** [comment]
Hi @ethansheffield, you might be affected by https://github.com/bigcommerce/stencil-cli/issues/1189#issuecomment-2048326651

**Comment by ethansheffield** [comment]
@jairo-bc I wish you nothing less than 1,000 blessings my friend 🙌
