### ISSUE TITLE
Evaluate subexpressions before assembling templates

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#212]
I am new to node and handlebars, but this request is based on the debugging I've attempted so far. I'm trying to load a partial by passing the name of the partial as a variable. In other words, I'd like to do something like this:

```
{{> components/common/panel content="components/common/category-images" title="Popular Categories"}}
```

Then, in the `panel.html` file, I want to load the `content` partial as the content of the panel. Something like this:

```
<div class="panel">
  <h1>{{title}}</h1>
  <div class="panel-body">
    {{> (lookup . 'content') }}
  </div>
</div>
```

This does not seem to work. I receive an error that the partial `components/common/category-images` does not exist. My debugging so far seems to indicate that this is happening because the `templateAssembler.js` file runs before the subexpression is evaluated, so the `components/common/category-images` partial never gets loaded.

I looked into the `dynamicComponent` helper, but that still does not seem to fit this use-case because the `basePath` would need to be known before the program runs so that all of the templates in that path can be loaded (at least I think that's how `dynamicComponent` works).

Is there any way to accomplish what I'm trying to do here? Any help would be much appreciated. Thank you!

**Comment by hegrec** [comment]
The only way it would work in the system now is to reference the partials from within your `panel.html` file as part of consecutive if statements that would look at an arbitrary key `content` that you would pass in.


Like this: `{{> components/common/panel content="components/common/category-images" title="Popular Categories"}}`


```
<div class="panel">
  <h1>{{title}}</h1>
  <div class="panel-body">
    {{#if content === "components/common/category-images"}}
        {{> components/common/category-images}}
    {{/if}}
  </div>
</div>
```

For future questions, please checkout our help forum here, because the github issues are not monitored by us often: https://developer.bigcommerce.com/help/

**Comment by kylebolstad** [comment]
@flyingL123 Did you ever find a way to get this working? We are attempting to do the same thing, but are hitting a brick wall with the BigCommerce version of Stencil Handlebars.

**Comment by kylebolstad** [comment]
@hegrec The 

> The only way it would work in the system now is to reference the partials from within your `panel.html` file as part of consecutive if statements that would look at an arbitrary key `content` that you would pass in.
> 
> Like this: `{{> components/common/panel content="components/common/category-images" title="Popular Categories"}}`
> 
> ```
> <div class="panel">
>   <h1>{{title}}</h1>
>   <div class="panel-body">
>     {{#if content === "components/common/category-images"}}
>         {{> components/common/category-images}}
>     {{/if}}
>   </div>
> </div>
> ```
> 
> For future questions, please checkout our help forum here, because the github issues are not monitored by us often: https://developer.bigcommerce.com/help/

As of the time of this comment, the help page says "Oops! This page doesn't exist."

**Comment by flyingL123** [comment]
@kylebolstad it's very ugly, but if you place your partials in handlebars comments, the stencil parser will pick it up. So you could list out all the possible values somewhere in a handlebars comment. In other words, in some page file, or maybe your layout file, do something like this:

```
{{!--
    {{> components/common/possible-partial-1}}
    {{> components/common/possible-partial-2}}
    {{> components/common/possible-partial-3}}
--}}
```

Now, handlebars will "know" about these partials, so if you try something like this, it should work:

```
{{> components/common/panel content="components/common/possible-partial-1" title="Partial 1"}}
```

This was a long time ago, so you'll have to try it to be sure.

**Comment by kylebolstad** [comment]
According to https://handlebarsjs.com/partials.html:

`{{> (lookup . 'myVariable') }}` should be supported.

But the BigCommerce template assembler is not allowing it. 

`'myVariable'` needs to be a function (and not a string), but there doesn't seem to be any supported method in BigCommerce to do this. This is why it results in the error that says the partial doesn't exist.

@hegrec @mcampa Is this something that can be supported with a change to `stencil-paper`?
