### ISSUE TITLE
Editor plugin missing

### ISSUE THREAD

**Issue by ghost** [bigcommerce/stencil-cli#219]
Having an issue with a missing editor plugin. 

➜  article15-store nvm use 4.4
Now using node v4.4.0 (npm v2.14.20)
➜  article15-store node -v && stencil -V
v4.4.0
1.3.4
➜  article15-store stencil start -e --tunnel

``````
                                 `+h
                               `+ddd
                             .oddddd
                           .oddddddd
                         -sddddddddd
                      `-sddddddddddd
                     -shdddddddddddd
                     ...-:+ydddddddd
                `......`   `+ddddddd
                -ddddddh-    ddddddd
            `   .yyyyyyo.  `+ddddddd
          .o/    `````    :ydddddddd
        -ohd+   `//////:` `.sddddddd
      -sdddd+   -ddddddds   `hdddddd
    :sdddddd+   .sssssso-   `ddddddd
  :ydddddddd+              -yddddddd
/yddddddddddy+++++++++++oshddddddddd
``````

 `/hdddddddddddddddddddddddddddddddddddd
/hdddddddddddddddddddddddddddddddddddddd
---

BigCommerce Stencil
---

module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/rafael/.nvm/versions/node/v4.4.0/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/StencilEditor'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.internals.parsePlugin (/Users/rafael/.nvm/versions/node/v4.4.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/glue/lib/index.js:192:23)
    at /Users/rafael/.nvm/versions/node/v4.4.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/glue/lib/index.js:102:36
    at Array.forEach (native)
    at /Users/rafael/.nvm/versions/node/v4.4.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/glue/lib/index.js:100:49
    at /Users/rafael/.nvm/versions/node/v4.4.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/glue/lib/index.js:115:9
    at iterate (/Users/rafael/.nvm/versions/node/v4.4.0/lib/node_modules/@bigcommerce/stencil-cli/node_modules/glue/node_modules/items/lib/index.js:35:13)
➜  article15-store

Has there been a breaking change?

**Comment by disgogo** [comment]
I also confirm this issue.

**Comment by hegrec** [comment]
This has been fixed once you update to the latest version of the code. For future questions or issues, please see our help forum here: https://developer.bigcommerce.com/help/ because we do not monitor github issues very often
