### ISSUE TITLE
`stencil bundle` fails if there is a directory in the project path with `.html` in the name

### ISSUE THREAD

**Issue by jnorth** [bigcommerce/stencil-cli#252]
This can be reproduced by installing stencil-cli to a theme locally, and running `stencil bundle`. The `ThemeConfig.prototype.getSchema` method uses `**/*.html` and doesn't check if it is a file or directory. The `hapi` modules contains the following folder: `node_modules/inert/test/directory/invalid/index.html/`

```
$ stencil bundle
Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Generating Manifest Started...
JavaScript Bundling Started...
ok -- Language Files Parsing Finished
ok -- Manifest Generation Finished
ok -- SCSS Parsing Finished
failed  -- EISDIR: illegal operation on a directory, read
/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:78
            throw err;
            ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

**Comment by mcampa** [comment]
This problem has been solved. Please upgrade by running `npm install -g bigcommerce/stencil-cli`

**Comment by huyenta92** [comment]
I think you run stencil start and stopped it before completing the process. This case, you only need to run stencil bundle again
