### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by CreativePlay** [bigcommerce/stencil-cli#271]
I'm getting stuck on the initial install. 

`npm install -g bigcommerce/stencil-cli`

Returns the following error:
`> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080`

Seems like that github link is dead. Thoughts?

**Comment by mcampa** [comment]
TL;DR You are probably using a not supported version of node. Use node 4.x.x

We are using an old version of `node-sass` that depends on node version 4 or older, but we are in the process of upgrading it. In the meantime please use node 4. I recommend using `nvm` to manage your node versions https://github.com/creationix/nvm

I'll keep this issue open to track the progress and notify you when you can upgrade.

**Comment by mcampa** [comment]
You can now use node 6 & 7 with stencil-cli

- Install  6 or 7 
- Run `npm install -g @bigcommerce/stencil-cli`
