### ISSUE TITLE
problem starting stencil - error after stencil init 

### ISSUE THREAD

**Issue by customBarres** [bigcommerce/stencil-cli#272]
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/michalpellicone/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)

**Comment by dstaley** [comment]
It looks like you might be trying to run `stencil init` within your home directory. You'll need to `cd` into the folder you cloned Stencil into.

```
git clone https://github.com/bigcommerce/stencil
cd stencil
npm install
stencil init
```

**Comment by customBarres** [comment]
Brilliant!  Thank you Dylan worked ;-) 
I spent hours trying to figure it out.
You rock!!!!

Thanks again.
Michal Pellicone | CUSTOM BARRES, LLC
436 W Commodore Blvd. • Suite 28 | Jackson, NJ 08527
w. http://www.custombarres.com <http://www.custombarres.com/>  e. info@custombarres.com <mailto:info@custombarres.com> p. 848.245.9464
