### ISSUE TITLE
Managing multiple sites

### ISSUE THREAD

**Issue by enkota** [bigcommerce/stencil-cli#274]
Hi! 

We are in the process of moving towards the stencil localhost development route. 

As we build multiple BigCommerce sites for clients, we have to create a new stencil install for each site. To clarify do we need to run `npm install` for each new site? What is the best way to manage multiple stencil sites locally?

Currently we clone the base theme into a new directory and run the `npm install` command and `stencil init` for each project.

Thanks!

**Comment by mcampa** [comment]
If you are developing multiple themes you will need to run `npm install` on each of the theme directories. This is because each theme could have different dependencies.

**Comment by enkota** [comment]
@mcampa Brill, thanks for clarifying. Bit of a hassle but can understand why so 👍

**Comment by mcampa** [comment]
@enkota you only need to run `npm i` once. If storage space is an issue you could symlink all `node_modules` directories
