### ISSUE TITLE
Browsersync issues with custom files

### ISSUE THREAD

**Issue by enkota** [bigcommerce/stencil-cli#284]
Hey,

We are using a custom.scss file within the assets folder. The file is working as intended and compiling. It's appearing on the terminal that browser sync is noticing the changes however does not refresh the page for that file. Is there another step I am missing out here that I need to add new sass files to?

Thanks,

[BS] File event [change] : /Users/Bigcommerce/5ive1/stencil/assets/css/custom.css

**Comment by mcampa** [comment]
Changes to scss files only refresh the stylesheets, not the entire page.

**Comment by enkota** [comment]
@mcampa Thanks for the reply, yes I understand but the changes are not being made on the page when saving the style changes.

**Comment by Bshally** [comment]
This is also happening to me, but is the case with all .scss files. The file event is registered in the terminal, but then none of the changes are injected into the browser and no notification pops up in the top right corner as it should to signal this happened.

**Comment by enkota** [comment]
Yea, essentially any changes made within the custom.scss file (has been imported via theme.scss) will not trigger the live reloading of browsersync. As @Bshally has mentioned, the file event is registered in terminal but not refreshed on save.

**Comment by mcampa** [comment]
investigating...

**Comment by enkota** [comment]
Thanks @mcampa will test out in work on Tuesday!
