### ISSUE TITLE
JS bundles not being compressed

### ISSUE THREAD

**Issue by dwest-teo** [bigcommerce/stencil-cli#287]
Not sure if this is the right place for this issue or not, but the problem began with an update to stencil-cli so hopefully it's relevant here!

For some reason my JS bundles are consistently being served without gzip compression since this morning's required stencil-cli update.  I know this is not strictly an issue with stencil-cli since the problem is occurring server-side, but I'm wondering if something happened with `stencil bundle` that would be causing this?

A theme that I bundled last night with the prior version of stencil-cli works as expected when deployed to a live store, the JS bundle gets compressed from a raw 998.5KB down to 281.7KB.  The same, unmodified theme bundled with today's updated stencil-cli is being served at the full 998.5KB without compression.  I've tested this in several browsers, via webpagetest and PageSpeed Insights, and with several different themes/JS bundles.  I've uninstalled and reinstalled stencil-cli several times, cleared npm cache, spun a prayer wheel, etc...same result with any JavaScript bundled in stencil-cli since the update.

If it's helpful, I'm using the following known-working dev environment:
macOS 10.12.3
node v4.4.5
npm v2.15.5

Any ideas?

**Comment by chrisboulton** [comment]
Hey @dwest-teo - this is very interesting indeed. We have been doing some work with our CDN recently, but we shouldn't be experiencing problems like this. Can you share the URL of one of the JS bundles you're seeing that's not compressed? I'd like to take a look at it. If you can't post it publicly, feel free to email me: chris@bigcommerce.com.

Thanks!

**Comment by dwest-teo** [comment]
Thanks Chris, sending you an email as we speak!

**Comment by dwest-teo** [comment]
Just an update, about an hour ago my JS bundle started coming across the wire with gzip enabled.  I appreciate you guys looking in to the issue!

**Comment by chrisboulton** [comment]
We actually haven't made any platform changes on our side that would have "fixed" this. From our end, we're still looking into it but it looks like what's happening is our CDN is caching the uncached objects (as it should), but then sometimes serving them up instead of compressing them for a client requesting a compressed version.

**Comment by dwest-teo** [comment]
That's definitely odd.  I only ever saw this issue manifest on my main JS bundle (hence my reasoning for posting the issue here)...never on any other assets from the CDN.  My theme uses code splitting with webpack-generated chunks loaded dynamically from the same CDN directory as the main bundle, and there was never a problem with the chunk's compression.  Strange that this problem would be contained to a single file, especially across multiple test deployments.

**Comment by dwest-teo** [comment]
Well it appears I spoke a little too soon unfortunately.  Everything was back to normal for a little over an hour, but now all of my JS assets are being served uncompressed...including the aforementioned chunks.  The issue is still contained to only my JS assets, everything else from the CDN is compressed...but now I'm seeing the problem across multiple files rather than just the main bundle.
