### ISSUE TITLE
[Stencil Bigcommerce] I follow the tutorials in making new page but the url is 404

### ISSUE THREAD

**Issue by ellemaker** [bigcommerce/stencil-cli#292]
See attachment
![screenshot_1](https://cloud.githubusercontent.com/assets/4677416/24980836/8c74c222-200c-11e7-982f-f215070d00b6.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/4677416/24980837/8c7ed726-200c-11e7-9ecc-46a85d23618a.jpg)

**Comment by ellemaker** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/4677416/24980885/c3554b22-200c-11e7-8a0d-dd208e1aaea5.jpg)

**Comment by mcampa** [comment]
The page needs to exist in your store.

⚠️ You are exposing your api token to the public. For security reason I changed your token. Please log in to your store control panel to get the new token.
