### ISSUE TITLE
New bundles won't load CSS

### ISSUE THREAD

**Issue by dwest-teo** [bigcommerce/stencil-cli#304]
Not sure if this is a problem with bundling or a CDN issue, but figured I'd create an issue here either way.

All day today I've been unable to deploy newly bundled themes.  Themes are bundling and uploading without error, but when I activate the uploaded themes no CSS loads due to a 502 error.  Here's a URL of a CSS file from a recent attempt for reference: https://cdn2.bigcommerce.com/n-d57o0b/k2r6aoh/stencil/37ed6ed0-171d-0135-70db-525400dfdca6/css/theme-4a172ef0-171d-0135-3b93-525400dfdca6.css

**Comment by dwest-teo** [comment]
This issue is still ongoing.  To clarify my above post, here's a screenshot with devtools open.  Note no CSS is applied to the page, the main CSS bundle fails with a 502 from the CDN.  Not sure if this is an issue with the hashed filename during bundling, or (more-likely I suspect) a CDN error.

![css-502](https://cloud.githubusercontent.com/assets/13018265/25919101/9f1f484e-359b-11e7-9133-74e9a94fc4f6.jpeg)

**Comment by mcampa** [comment]
Investigating

**Comment by mcampa** [comment]
Hi @dwest-teo, thanks for your patience. I just deploy a fix to production. Should be working now.

**Comment by dwest-teo** [comment]
Works like a charm, thanks very much for your help @mcampa!
