### ISSUE TITLE
{ [Error: Cannot find module './_an-object'] code: 'MODULE_NOT_FOUND' }

### ISSUE THREAD

**Issue by patelbj3** [bigcommerce/stencil-cli#314]
Hi,
I am unable to start stencil on local host.  I keep getting the following error...
Please advise at your earliest convenience,
Thank you,
Michal

Node Version: v4.8.1
```
-------------------------------------------------

{ [Error: Cannot find module './_an-object'] code: 'MODULE_NOT_FOUND' }
[BS] File event [change] : /Users/custombarres-imac2/Desktop/themes/stencil/assets/css/cb_fonts.css
[BS] File event [change] : /Users/custombarres-imac2/Desktop/themes/stencil/assets/css/checkout.css
[BS] File event [change] : /Users/custombarres-imac2/Desktop/themes/stencil/assets/css/invoice.css
[BS] File event [change] : /Users/custombarres-imac2/Desktop/themes/stencil/assets/css/maintenance.css
[BS] File event [change] : /Users/custombarres-imac2/Desktop/themes/stencil/assets/css/optimized-checkout.css
[BS] File event [change] : /Users/custombarres-imac2/Desktop/themes/stencil/assets/css/theme.css
[BS] Proxying: http://localhost:3001
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3005
    External: http://192.168.1.11:3005
 -------------------------------------
          UI: http://localhost:3006
 UI External: http://192.168.1.11:3006
 -------------------------------------
[BS] Watching files...
```

**Comment by mcampa** [comment]
Looks like you are trying to import `_an-object` somewhere in your theme.

Can you please find `_an-object` in you theme files and remove/comment that line and let me know if the error persist?

**Comment by patelbj3** [comment]
I solved this error.Now I have another error.Now when we try stencil bundle it gives error: 

✖ 167355 problems (162000 errors, 5355 warnings)

/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:253
            throw err;
            ^

Error: Please fix the above Javascript errors.
    at runLintTask (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/lib/bundle-validator.js:268:18)
    at /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:396:17)


I check all the js files and I tried to solve it but its giving us the same error.Can you please help me to solve this error.

**Comment by mcampa** [comment]
Before continuing, can you confirm that `stencil-cli` is working fine on a clean copy of https://github.com/bigcommerce/cornerstone? Run `stencil bundle` on a clean copy and Cornerstone and let me know.

If it runs fine and your theme is based on Cornerstone, run a diff to see if any of your changes is producing this errors. Seems like you have javascript errors.

**Comment by mcampa** [comment]
Can you please send me a copy of the theme to mario.campa@bigcommerce.com?

**Comment by patelbj3** [comment]
ya sure.I am sending you my themes on you email address.

**Comment by patelbj3** [comment]
Can you check you email.I sent you zip file using we transfer.

**Comment by patelbj3** [comment]
I have one more question.How do I view category page and product page on the local host.

**Comment by mcampa** [comment]
The main problem is that you added extra js files to `assets/js` directory, that are not compliant with eslint rules. 

`assets/js` is the only directory that is lintted  with Eslint.

You can place these files in a different directory, say `assets/scripts` for example.

But I encourage you to read the documentation and use to include this scripts in the bundle, using webpack/npm

It would be useful also to read how Webpack works and how "import" modules into your theme

**Comment by patelbj3** [comment]
I run this clean copy of cornerstone and it works.It generate zip file which we need it mean my stencil cli is working properly.

**Comment by patelbj3** [comment]
what is webpack and how to use it?

**Comment by jasonherbst8** [comment]
Here's an article about webpack that should help you: http://blog.andrewray.me/webpack-when-to-use-and-why/.  Also please take a look at official webpack documentation: https://webpack.github.io.

With respect to category and product pages -- are you receiving a specific error when trying to access those pages?

**Comment by patelbj3** [comment]
what would be the path to access  category and product pages ? on
  localhost:3000 ???

**Comment by jasonherbst8** [comment]
that's specific to your store.  are you able to navigate to those pages via the browser?

**Comment by patelbj3** [comment]
@jasonherbst8 I dont the location from where I can fin those pages.Can you please help me to find those pages.I can share you my file also if you want to take a look at it.

**Comment by jasonherbst8** [comment]
Can you access your store's homepage?  It should be simply a matter of clicking from the homepage to navigate to category and product pages.

**Comment by jasonherbst8** [comment]
looks like you have an unclosed conditional at templates/components/products/product-view.html line 310  -- missing {{/if}}

**Comment by patelbj3** [comment]
@jasonherbst8 I am trying to go on the product page but when I click on any product it give me error .Error is : {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

Can you help me to solve this error.
