### ISSUE TITLE
"TypeError: callback is not a function" after upgrading to stencil 1.12.0

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#318]
I just upgraded to the latest version of stencil-cli, and now getting an error anytime I edit, or simply just open any template file. I upgraded from version 1.8 by running:

`npm install -g @bigcommerce/stencil-cli`

After the new version installed, I ran `stencil start`, and everything seemed to be working fine.

Then, I opened a template file to edit `vi templates/components/common/header.html`. As soon as the file opens, stencil-cli outputs the following error, and shuts down:

```
/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:26
            return callback(err);
                   ^

TypeError: callback is not a function
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:26:20
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:91:20
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:998:13)
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:906:16
    at ReadFileContext.callback (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:112:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

This occurs everytime a template file is openend or edited. It does not seem to occur when I edit a sass file. So far, I have only seen it when editing/opening/saving something in the `templates/` directory.

I am running node `v4.2.1` in case that matters.

Any idea why this is happening all of a sudden? Is there some sort of bug with the latest version?

**Comment by flyingL123** [comment]
Not sure if this helps, but when I downgrade back to version 1.8.0, the issues goes away. However, when I save certain files, I still see an error in the cli output even with version 1.8.0. For example, when I save the file `templates/components/common/header.html`, the cli outputs:

```
[Error: The following template(s) are/is missing:
components/common/.header.html]
```

The sever does not shut down. It continues to run, but just outputs the error. It does not show this error for all files. For example, I have another template file called `templates/components/category/header.html`. When I save this file, I do not see any errors in the console.

Could this possibly have something to do with `.swp` files? I'm just mentioning this in case it is related to the bug I am reporting in version 1.12.0. It seems similar because in version 1.12.0, when I `console.log(err)` in between line 25 and 26 in `template-assembler.js`, the full output is now:

```
[Error: The following template(s) are/is missing:
function (err, v) {
            results[index] = v;
            callback(err);
        }]
/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:27
            return callback(err);
                   ^

TypeError: callback is not a function
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:27:20
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:92:20
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:998:13)
    at /Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/async/dist/async.js:906:16
    at ReadFileContext.callback (/Users/myusername/.nvm/versions/node/v4.2.1/lib/node_modules/@bigcommerce/stencil-cli/lib/template-assembler.js:113:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

**Comment by junedkazi** [comment]
1.12.1 has been released.
