### ISSUE TITLE
Push failing

### ISSUE THREAD

**Issue by jbeanky** [bigcommerce/stencil-cli#322]
Push command fails with 503 status code.  Verified that I can POST using the Themes API.  Bundle also works when used separately.  Directory is initialized and can run using the start command.  I am using a trial store.

**Comment by jbeanky** [comment]
Full error message 'StoreHashReadError: Response Error: 503 Service Unavailable'.  I have also confirmed that I can curl /admin/oauth/info using my store URL.  The storehash is part of the response.

**Comment by mjschock** [comment]
@jbeanky - could you please send me the store url to michael.schock@bigcommerce.com so i can diagnose the issue.

**Comment by mjschock** [comment]
@jbeanky - are you using OAuth credentials with 'Modify' scope?

**Comment by jbeanky** [comment]
@mjschock Thought I had tried this before, but I found the issue with some trial and error.  The push command will only work without a trailing slash in the store URL when running the init command.  If I add the trailing slash, I get the 503 error from the push command.  The start command still works with or without trailing slash in store URL.

**Comment by mjschock** [comment]
@jbeanky - ah, good to know.  we've created a ticket to allow the trailing slash.  glad it's working!

**Comment by HeatherBohrer** [comment]
When performing the BUNDLE I was receiving the hash error. I resolved that aspect and now when I go to PUSH I continually get job failed at the processing point. 
![git](https://user-images.githubusercontent.com/20432012/30606354-1405ef8e-9d37-11e7-8d5b-ad5ace35d352.PNG)

**Comment by diegovogel** [comment]
This error report saved me again! Thanks @jbeanky 
Perhaps a note could be added to the Stencil docs? "Make sure store URL does not end with a slash". 
Especially since urls end with a slash by default when copied from the address bar. At least in Chrome.

**Comment by ohabash** [comment]
For me this problem was caused by a trailing slash in `.stencil`

was `"normalStoreUrl": "https://store-xxx.mybigcommerce.com/"`
should be `was `"normalStoreUrl": "https://store-xxx.mybigcommerce.com"``
