### ISSUE TITLE
Stencil Bundle error

### ISSUE THREAD

**Issue by thesquaremedia** [bigcommerce/stencil-cli#324]
Hi im geting this error when running `stencil bundle`

```
AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\bin\stencil-bundle:66
        throw err;
        ^
```
Also it seems to fail to gather this files.
failed  -- The following template(s) are/is missing:
components/common/icons/icon-defs
components/common/cookie
components/common/header-laparis2
components/common/header
components/common/body
components/common/footer

i checked the template folder and the files are there.

**Comment by PreciselyAlyss** [comment]
@thesquaremedia what version of the stencil cli are you using?

**Comment by PreciselyAlyss** [comment]
@thesquaremedia The fix has been merged. You can pull down a copy of the latest cornerstone files from github or you can wait for the next cornerstone theme release. 

Thanks for the report
