### ISSUE TITLE
Response Error 503 using stencil push

### ISSUE THREAD

**Issue by snoogans235** [bigcommerce/stencil-cli#326]
Running macOS 10.12.5, and modifying the cornerstone theme (not sure of the version though).  We have done some extensive updates to the header and footer, as well as add in our own templates, and javascript.  I am able to bundle the package without any problem, but when I try to push I get the error: 
`not ok -- StoreHashReadError: Response Error: 503 Service Unavailable
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
`
If you need the zip file let me know.

**Comment by PreciselyAlyss** [comment]
@snoogans235 are you using oauth or basic auth credentials?

**Comment by snoogans235** [comment]
@PreciselyAlyss we are using oauth.  I did try to upload the design, but the request returned
```
{"status":400,
"title":"Cannot find payload\/event classes for the events.",
"type":"https:\/\/developer.bigcommerce.com\/api#api-status-codes"}
```

**Comment by elliot-hagerty** [comment]
+1 I'm getting the exact same error. Also using oauth.

`not ok -- StoreHashReadError: Response Error: 503 Service Unavailable
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.`

**Comment by jbeanky** [comment]
Could be same as my closed issue #322. The push command will only work without a trailing slash in the store URL.  Run the init command again without a trailing slash in your store URL.

**Comment by snoogans235** [comment]
That fix took care of the first issue!  but now I'm not able to upload the theme all the way....
````
Processing [=========                                           ] 18%; ETA: 6.5not ok -- JobCompletionStatusCheckError: Job Failed
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
````

**Comment by jbeanky** [comment]
Still having this issue? Have you tried uploading a different theme? Or the unmodified cornerstone theme bundle? How big is your theme bundle? Looking at the code, it seems like you must be getting some kind of error from the BigCommerce API. Maybe they could diagnose the issue by looking at your account on the backend. If you upload your bundle here, I can try pushing it to a store.

**Comment by snoogans235** [comment]
Figured out, what the upload problem was.  We were looking at what we could do to get a featured category on the homepage, and left in featured category links in config.json.  I guess since they didn't match up with schema.json, BC's api stopped the upload.

**Comment by steve-ross** [comment]
whoa trailing slash breaks this... seems like the tool could account for it instead of having to google for the workaround, right?
