### ISSUE TITLE
Stencil push  & bundle errors

### ISSUE THREAD

**Issue by creativewhs** [bigcommerce/stencil-cli#335]
****This error occurs when I use stencil init**** 

$ stencil push
not ok -- StoreHashReadError: Response Error: 404 Not Found
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.

**This error occurs when I use stencil bundle** 

$ stencil bundle
Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- SCSS Parsing Finished
ok -- Theme Schema Building Finished
failed  -- The following template(s) are/is missing:
core/account/_private/layout-heading
core/account/_private/navigation
core/account/_private/layout-heading
core/alerts/alert-error
core/alerts/alert-success
core/alerts/alert-error
core/alerts/alert-success
core/alerts/alert-error
components/header/shipping-messages
svg/account
svg/account
svg/account
components/header/currency-selector
components/header/shipping-messages
components/header/site-branding
svg/wishlist
svg/cart
svg/cart
components/header/site-navigation-left-align
components/header/site-navigation-center-align
components/header/site-navigation-right-align
components/common/navigation
components/common/navigation-top-level
components/footer/brand-navigation
components/common/social-media-links
svg/visa
svg/mastercard
svg/amex
svg/discover
svg/paypal
svg/applepay
svg/close
components/mini-cart/mini-cart-contents
components/common/search-form
components/common/multi-level-nav-item
svg/arrow-down
components/common/multi-level-nav-item
components/common/multi-level-nav-item
svg/account
svg/account
svg/wishlist
svg/cart
components/header/currency-selector
svg/close
components/common/search-form
svg/close
core/auth/login
svg/close
core/auth/forgot-password
C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\bin\stencil-bundle:52
        throw err;
        ^

Error: The following template(s) are/is missing:
core/account/_private/layout-heading
core/account/_private/navigation
core/account/_private/layout-heading
core/alerts/alert-error
core/alerts/alert-success
core/alerts/alert-error
core/alerts/alert-success
core/alerts/alert-error
components/header/shipping-messages
svg/account
svg/account
svg/account
components/header/currency-selector
components/header/shipping-messages
components/header/site-branding
svg/wishlist
svg/cart
svg/cart
components/header/site-navigation-left-align
components/header/site-navigation-center-align
components/header/site-navigation-right-align
components/common/navigation
components/common/navigation-top-level
components/footer/brand-navigation
components/common/social-media-links
svg/visa
svg/mastercard
svg/amex
svg/discover
svg/paypal
svg/applepay
svg/close
components/mini-cart/mini-cart-contents
components/common/search-form
components/common/multi-level-nav-item
svg/arrow-down
components/common/multi-level-nav-item
components/common/multi-level-nav-item
svg/account
svg/account
svg/wishlist
svg/cart
components/header/currency-selector
svg/close
components/common/search-form
svg/close
core/auth/login
svg/close
core/auth/forgot-password
    at C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\lib\template-assembler.js:93:29
    at C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:998:13)
    at C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:906:16
    at C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:998:13)
    at C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:906:16
    at C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:998:13)
    at C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\async\dist\async.js:906:16

**Comment by creativewhs** [comment]
Also getting this error for stencil bundle:

$ stencil bundle
Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- SCSS Parsing Finished
ok -- Theme Schema Building Finished
failed  -- EMFILE: too many open files, open 'C:\Users\jolen\Documents\Stencil\Peak-1.12.10\templates\pages\account\orders\invoice.html'
C:\Users\jolen\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\bin\stencil-bundle:52
        throw err;
        ^

Error: EMFILE: too many open files, open 'C:\Users\jolen\Documents\Stencil\Peak-1.12.10\templates\pages\account\orders\invoice.html'
    at Error (native)

**Comment by PreciselyAlyss** [comment]
@creativewhs The fix has been merged. You can pull down a copy of the latest cornerstone files from github or you can wait for the next cornerstone theme release.

Thanks for the report
