### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by thetechie92** [bigcommerce/stencil-cli#338]
Trying to install the stencil-cli and everytime I am getting this:

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1

npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by mcampa** [comment]
Your package.json is not valid JSON. You have an invalid unicode character at 1:1 in the file
