### ISSUE TITLE
Feature request: allow setting environment variables

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#340]
We maintain 2 BigCommerce stores. One is a development store and the other is our live production store. Each store makes API calls to our self-hosted servers to retrieve various data and product information that we store outside of the BigComerce store.

The various URLs and other information for the API is stored in the theme's `config.json` file so that the theme will have the appropriate URLs to make the calls. For example:

```
{
  "internal_api": {
    "base": "//internal-api.my-domain.com",
    "products": "/products",
    "reviews": "/product-reviews"
  }
}
```

However, for our development store, which connects to our development API server, I have to manually change the `base` to `//dev.internal-api.my-domain.com`. There are other changes required as well for other parts of the file. This is just one example.

It would be very useful if there was some way for me to set an environment variable (or something similar) in each of the repos for the product and development store, and refer to those variables from the `config.json` file instead of having to manually alter them.

Is this currently possible, or is there some way to add this feature?

**Comment by mcampa** [comment]
You could use `variations` in `config.json`. Create one variations called `live` and another called `dev`, then pass the variation as a parameter:
```
stencil start -v dev
stencil start -v live
```

In your `config.json`

```json
{
  ...
  "variations": [
    {
      "name": "live",
      ...
      "settings": {
        "api_url": "//internal-api.my-domain.com",
        ...
     },
    {
      "name": "dev",
      ...
      "settings": {
        "api_url": "//internal-api.my-domain.dev",
        ...
     }
  ]
}
```

Then you can access `context.theme_settings.api_url` in you javascript here https://github.com/bigcommerce/cornerstone/blob/master/assets/js/app.js#L61

**Comment by flyingL123** [comment]
Wow that is such a great idea. Thank you for the suggestion. I never thought of that.
