### ISSUE TITLE
Stencil Push:  JobCompletionStatusCheckError

### ISSUE THREAD

**Issue by RikuKitade** [bigcommerce/stencil-cli#344]
### Expected behavior
To process custom theme successfully.

### Actual behavior
Uploading theme works,  the following error is produced when the theme is processing : "not ok -- JobCompletionStatusCheckError: Job Failed".

### Steps to reproduce behavior
I used stencil push and everything was in the green up until the console logged: 

Processing [============                                                                                        ] 12%; ETA: 8.9snot ok -- JobCompletionStatusCheckError: Job Failed
![console](https://user-images.githubusercontent.com/5893560/31210823-c40eded6-a949-11e7-87e5-41edb0959550.png)

UPDATE: I also tried the above with a clean cornerstone project and I received the exact same error.

**Comment by mcampa** [comment]
@mjschock any ideas?

**Comment by mjschock** [comment]
@mcampa - either the status code from the jobs endpoint was not a 200 or the payload status was 'FAILED'.

the relevant block of code is here:  https://github.com/bigcommerce/stencil-cli/blob/master/lib/theme-api-client.js#L76-L80

@RikuKitade - in this case i would guess it's just an intermittent error.  perhaps it got a 502 during one of the checks.  do you see the theme in your store afterword?

if you have the time, you could log the status code and payload in the block above and let us know

**Comment by RikuKitade** [comment]
@mjschock 
Thanks for the reply. I do not see it in my store afterwards. When I tried to to upload it to the BigCommerce website, the theme does get uploaded, but while it is processing it gets cancelled and a red notiification shows up that says there was a problem processing my theme. Here's the what the console log displays:

![log](https://user-images.githubusercontent.com/5893560/31246719-27e0d9a4-a9c3-11e7-85fe-6d78d0ecfe30.png)

Also here is the red notification I got:

![image](https://user-images.githubusercontent.com/5893560/31246876-abe0ee38-a9c3-11e7-9889-ade092eb1ba4.png)

**Comment by mjschock** [comment]
@RikuKitade ah, it seems like there might be something wrong with the theme if it's failing for an upload in the control panel too.  do you see the same error if you try to upload a clean version of cornerstone?  i'm sending you an email now (to your address listed on your github account) where you can reply with your theme attached and i'll try diagnosing from my side

**Comment by RikuKitade** [comment]
@mjschock So uploading  and processing a clean version worked. I think i just forgot to do npm install earlier when I tried to upload the clean version. I'm sending you an email right now with a wetransfer link for my project. Thanks

**Comment by RikuKitade** [comment]
SOLVED: Thanks to @mjschock , I was able to fix the problem. Turns out that I had a video in the project folder that was taking up a lot of space (about 20 MB). I moved that video into WebDav and referenced it there instead. After making those changes, I was able to both upload and process my theme successfully.

Side note: If you have bunch of red errors while bundling (via 'stencil bundle' or 'stencil push', try removing the .eslintrc and .eslintignore files. That was another problem I ran into earlier.

**Comment by mcampa** [comment]
I'm glad you solved the issue. 

Is a bad idea to  delete`.eslintrc` or `eslintignore`. You should fix your eslint errors first, this prevents bugs in your theme. For more info https://eslint.org/

Follow up ticket to improve the error message: https://jira.bigcommerce.com/browse/MERC-2888

**Comment by brandonjp** [comment]
@mcampa @mjschock any traction yet on better error messages?  https://jira.bigcommerce.com/browse/MERC-2888
