### ISSUE TITLE
not ok -- StoreHashReadError: Response Error: 503 Service Unavailable

### ISSUE THREAD

**Issue by aisflat439** [bigcommerce/stencil-cli#349]
I created a pull request for this that serves a more helpful error but didn't really have time to solve it.

# StoreHashReadError

In `.stencil`
```
  "normalStoreUrl": "http://awesomeBCSandbox.mybigcommerce.com/",
```
throws this error

```
  "normalStoreUrl": "http://awesomeBCSandbox.mybigcommerce.com",
```
will fix this error

**Comment by mjschock** [comment]
@aisflat439 fixed with https://github.com/bigcommerce/stencil-cli/pull/369
