### ISSUE TITLE
Anyone reading this or you guys don't care?

### ISSUE THREAD

**Issue by vfonic** [bigcommerce/stencil-cli#365]

**Comment by junedkazi** [comment]
Sorry for the gaps in responses. We will try to do a better job at responding to people issues.

**Comment by vfonic** [comment]
Thanks, @junedkazi!

On Feb 21, 2018 12:31, "Juned Kazi" <notifications@github.com> wrote:

Closed #365 <https://github.com/bigcommerce/stencil-cli/issues/365>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bigcommerce/stencil-cli/issues/365#event-1485327895>,
or mute the thread
