### ISSUE TITLE
Stencil push stopped working

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#366]
Using stencil 1.12.1 and node v4.2.1,`stencil push` has suddenly stopped working for me. Here's what's happening:

```
$ stencil push
Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Generating Manifest Started...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Manifest Generation Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Theme task Finished
ok -- Template Parsing Finished
ok -- Zipping Files Finished
not ok -- ThemeUploadError: Server Error
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
```

That happens every time I run `stencil push`. However, if I just use `stencil bundle` and upload the theme manually through the BigCommerce UI, everything works fine:

```
$ stencil bundle
Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Generating Manifest Started...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Manifest Generation Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Theme task Finished
ok -- Template Parsing Finished
ok -- Zipping Files Finished
Bundled saved to: /Users/myusername/dev/stencil/MyTheme-1.1.2.zip
```

I then upload that zip file through the UI and apply it to the store and there are no problems. Any idea what is causing this? `stencil push` used to work fine for me and then suddenly I started getting these errors.

**Comment by emilian** [comment]
I am getting a different error with stencil push:

```$ stencil push
Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
ok -- Theme task Finished
Generating Manifest Started...
ok -- Manifest Generation Finished
ok -- Zipping Files Finished
ok -- Theme Upload Finished
Processing [============                                                                                        ] 12%; ETA: 52.1snot ok -- JobCompletionStatusCheckError: Job Failed
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.```

Receiving an error with the UI as well.

Any thoughts?

**Comment by junedkazi** [comment]
@flyingL123 @emilian if you could mail me privately details about the store you are working on I can take a quick look at the logs & get you more details or solutions. You can email me at "first-name.last-name@bigcommerce.com" You should be able to get my info on my profile page.

**Comment by flyingL123** [comment]
@junedkazi I am now getting the exact same error as @emilian. Using node v7.9.0 and stencil 1.14.0. I am also getting an error in the UI. Here's the full output:

Validating theme...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
clean-webpack-plugin: /Users/michaelleff/dev/syb-stencil-new/assets/dist has been removed.
(node:8666) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
ok -- Theme task Finished
Generating Manifest Started...
ok -- Manifest Generation Finished
ok -- Zipping Files Finished
ok -- Theme Upload Finished
Processing [============                                                                                        ] 12%; ETA: 9.3snot ok -- JobCompletionStatusCheckError: Job Failed
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.

I'm under a deadline to get these new theme out and this is obviously causing a major issue. Any advice on what to do to get the theme live?

**Comment by flyingL123** [comment]
Oddly, the same theme, with the same version of node and stencil work perfectly fine on my development store. stencil-push works as expected. What's going on here?

**Comment by flyingL123** [comment]
This is the error response in the control panel when trying to upload the theme:

> {"status":400,"title":"Cannot find payload\/event classes for the events.","type":"https:\/\/developer.bigcommerce.com\/api#api-status-codes"}

That is the response for the POST call to:

https://www.my-store.com/admin/events/stencil

The request has this payload:

> {"eventName":"ATHENA_EVENTS.PRIVATE_THEME_PROCESSING_FAILED","payload":{"fileName":"MyStore-1.1.2.zip","jobId":"7d05734119f9ace8726aa11ffc6b58da","message":"[{\"error\":\"tr_300\",\"message\":\"There was a problem with the zip file. (TR-300)\"}]"},"options":{"producerFlow":"storefront manager","producerSource":"BIGCOMMERCE CONTROL PANEL"}}

**Comment by flyingL123** [comment]
This page helped me:

https://stencil.bigcommerce.com/docs/uploading-a-custom-theme#section--a-name-errors-a-error-codes

I deleted the `assets/js/bundle.js` file and it fixed the problem.

**Comment by junedkazi** [comment]
@flyingL123 I am glad you were able to figure it out.

**Comment by junedkazi** [comment]
I am going to close this issue for now since the issues have been addressed. We have a PR coming out soon which will address the issue of surfacing the errors in a much better way via cli.
