### ISSUE TITLE
`stencil push` stopped working (2)

### ISSUE THREAD

**Issue by vfonic** [bigcommerce/stencil-cli#368]
I added couple of videos totalling 29MB. Ever since I can't push the theme. I removed the videos and push passes successfully. What's the file size limit for the theme? Can you please add better error message, so I don't have to try 5 times before figuring out it's not temporary network issue, but file size limit? Thanks!

It always stops at 12%. Here's the screenshot:
<img width="836" alt="screen shot 2018-02-19 at 19 48 56" src="https://user-images.githubusercontent.com/67437/36404028-2ef87362-15ae-11e8-9eeb-94c227b24d29.png">

PS I have less than 5 themes installed and the tool is still telling me to delete more themes. I'm wondering what will happen when I'm out of themes...

**Comment by junedkazi** [comment]
We have a limit on the size for the zip file which is 50 MB https://stencil.bigcommerce.com/docs/staging-and-submitting-a-theme#sizing-your-theme. 

We also have info in the dev docs on how to exclude static assets https://stencil.bigcommerce.com/docs/webdav-static-assets

**Comment by vfonic** [comment]
@junedkazi Thanks! I uploaded the video files to WebDAV and successfully pushed the theme!

I did a little bit more of investigation, in case it might help you put a better error message or if you want to investigate further:

I just ran `stencil bundle` and checked the zip file size. It's 45.4MB. (But it still fails on `stencil push`)

I then removed some of the assets I no longer need. The bundle size is 44MB now. I still can't push the theme.
I also tried: `stencil push -f Crystal\ Rock\ Custom\ Theme-1.9.3.zip` (from `stencil bundle`), but with no success.

The only thing that worked was moving the video files to WebDAV.

Thanks!

**Comment by junedkazi** [comment]
@vfonic can you check in the zip if any of the compiled/parsed templates are greater than 1MB. We have a hard limit of 1MB on template size. You might have to look into why they are growing to that size. We should have a PR coming out soon to surface the errors better.
