### ISSUE TITLE
Specifying Tunnel URL

### ISSUE THREAD

**Issue by richardtorres314** [bigcommerce/stencil-cli#370]
### Expected behavior
`stencil start --tunnel="my-private-site" // works`

### Actual behavior
`stencil start --tunnel="my-private-site" // doesn't works`

### Steps to reproduce behavior
In command line, run `stencil start --tunnel="my-private-site"`

**Comment by junedkazi** [comment]
It might be a regression when we did https://github.com/bigcommerce/stencil-cli/pull/362. I will have to dig into it to see what is happening.

**Comment by brandonjp** [comment]
I didn't even realize this was an option (until I was troubleshooting #538 )!  When `--tunnel` works I'm gonna be wishing this did too!

**Comment by junedkazi** [comment]
This should be fixed as part of 1.23.0 release. See https://github.com/bigcommerce/stencil-cli/blob/master/CHANGELOG.md#1230-2020-02-17 for more details. Please do open a new issue if the issue still persists.
