### ISSUE TITLE
Stencil Pull functionality

### ISSUE THREAD

**Issue by PeteyRev** [bigcommerce/stencil-cli#376]
Any plan to perhaps make a `stencil pull` command to get the stores current theme and unzip locally? I work on a lot of different clients' sites in which they will make changes to, so I constantly have to download their current theme and do this manually

**Comment by Lewiscowles1986** [comment]
Yes I've tried all download options and the stencil theme still looks different to the one installed on BigCommerce. It's frustrating to say the least given that I have all permissions.

**Comment by bookernath** [comment]
Great idea! I don't think we have any near-term plans for this, although PRs are welcome.

You can see the docs for our Themes API that we use for `stencil push` here - https://developer.bigcommerce.com/api/v3/themes.html

**Comment by junedkazi** [comment]
Fixed in https://github.com/bigcommerce/stencil-cli/pull/583
