### ISSUE TITLE
Stencil editor CLI fails to warn if schema.json is misformatted

### ISSUE THREAD

**Issue by scottcwilson** [bigcommerce/stencil-cli#378]
### Expected behavior
If you forget a comma or accidentally add a comma where one should not be in `schema.json`, the CLI should complain in the window where `stencil start -e` was used.

If you use `stencil start` and modify the `config.json` incorrectly, an error message is shown: 
```
Error: cornerstone/config.json - Parse error on line 191:
...lor": "#ffffff"    "footer-backgroundCo...
```

### Actual behavior
No error message is shown for the CLI theme editor when `schema.json` has a missing comma.  You have to figure out for yourself where the errant line in `schema.json` is.  

### Steps to reproduce behavior
Edit `schema.json` and remove a comma.  Refresh http://localhost:8181/ and you'll get a blank page.

**Comment by junedkazi** [comment]
This should be addressed as part of #405 and #413. Please re-open if it is still an issue.
