### ISSUE TITLE
cannot use @import in sass

### ISSUE THREAD

**Issue by jeremysimmons** [bigcommerce/stencil-cli#387]
### Expected behavior
no errors when using `@import`

### Actual behavior
{ Error: cook-footer\tablet.scss doesn't exist!
    at options.error (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\node-sass\lib\index.js:277:32)
  formatted: 'Error: cook-footer\\tablet.scss doesn\'t exist!\n        on line 458 of custom.scss\n>>                 @import "cook-footer/tablet";\n   ------------------------^\n',
  message: 'cook-footer\\tablet.scss doesn\'t exist!',
  column: 25,
  line: 458,
  file: 'custom.scss',
  status: 1 }

### Steps to reproduce behavior

node 8.11.2
stencil 1.14.3

Arrange files in assets/scss folder 

```
│   custom.scss
│               
├───cook-footer
    desktop.scss
    mobile.scss
    table.scss
```        

reference file in subfolder using `@import`
```
@media (min-width: $screen-medium) {
@import "cook-footer/tablet";
}
```

stencil start
load page referencing custom.scss in browser http://localhost:3000

**Comment by jeremysimmons** [comment]
Issue also there in node 6.9.5

**Comment by karen-white** [comment]
Hey @jeremysimmons , I tried to repro with the following file structure:
<img width="717" alt="import" src="https://user-images.githubusercontent.com/31664136/40751716-0595b642-6432-11e8-9898-92046119e09a.png">
Could you let me know if this matches what you have? In my test case, theme.scss imports custom.scss, which imports "cook-footer/tablet". CSS in the "cook-footer/tablet" file rendered on the storefront for me, and no error. 

In your file tree, I notice the filename is table.scss. Is that typo present in your actual file name, or just this example?

**Comment by jeremysimmons** [comment]
I'm on Microsoft Windows [Version 10.0.16299.64]... Your Sublime window chrome tells me your on OSx or a tricked out Linux.

**Comment by jeremysimmons** [comment]
> Could you let me know if this matches what you have? 

Yes. I think this is the same.
**theme.scss**
@import "custom";

**custom.scss**
```
#footer {
    .container {
        .footer-block {
            @media (min-width: $screen-medium) {
                @import "cook-footer/tablet";
            }
        }
    }
}
```

**cook-footer/tablet.scss**
```
.karen {
    color:white; /* family-name isn't a css property */
}
```

![image](https://user-images.githubusercontent.com/1406886/40851028-63071b98-6583-11e8-9962-b3319ce34f44.png)

![image](https://user-images.githubusercontent.com/1406886/40851386-89d4a3f2-6584-11e8-879d-3040d62eaa33.png)

![image](https://user-images.githubusercontent.com/1406886/40850965-34d9434a-6583-11e8-9d75-32b15051f8ea.png)

**Comment by karen-white** [comment]
@jeremysimmons Yep, that looks like the setup I was testing with. I'll try on Windows, and let you know what I find!

**Comment by karen-white** [comment]
@jeremysimmons On a PC, I did get the same error you were seeing. I can open an internal ticket to address it.

As a workaround, putting custom.scss in a directory resolved the error for me. The behavior seems to happen on Windows, when a top level file imports a top level file that imports something else.

**Comment by jeremysimmons** [comment]
> putting custom.scss in a directory resolved the error for me

This worked. 
```
Assets
|
+---scss
    |   theme.scss
    |   
    +---custom
        |   _custom.scss
        |   
        \---footer
                _desktop.scss
                _mobile.scss
                _tablet.scss
```

**theme.scss**
@import "custom/custom";

**_custom.scss**
@import "footer/tablet";
