### ISSUE TITLE
home banner 

### ISSUE THREAD

**Issue by bigmadness** [bigcommerce/stencil-cli#389]
after first  loop 1st banner image load slowly.

**Comment by karen-white** [comment]
@bigmadness Is there any additional detail you could provide on this, or a screencast video?

**Comment by bigmadness** [comment]
hi @karen-white safari, chrome 

![banner](https://user-images.githubusercontent.com/10583985/40870944-39a4d5f4-6652-11e8-99e9-334669488f64.gif)

**Comment by bigmadness** [comment]
I moved issue at https://github.com/bigcommerce/cornerstone/issues/1255
