### ISSUE TITLE
'stencil push' stopped by 'JobCompletionStatusCheckError: Job Failed'

### ISSUE THREAD

**Issue by dunxtand** [bigcommerce/stencil-cli#391]
### Expected behavior
Local theme files pushed to online store.

### Actual behavior
![screen shot 2018-05-31 at 2 18 20 pm](https://user-images.githubusercontent.com/12576940/40800173-9cf97478-64dd-11e8-8a88-a24a9e913f03.png)
I've contacted my store rep with this problem, and he told me to submit an issue. I've tried to push a number of times but I always get this same result. I always just use 'stencil push', without any options.

### Steps to reproduce behavior
N/A

**Comment by dunxtand** [comment]
@junedkazi thanks, should have tried this originally. I got this error message:
![screen shot 2018-06-05 at 10 17 36 am](https://user-images.githubusercontent.com/12576940/40983636-113bf710-68ae-11e8-9c75-0aa89f644ca0.png)
I wasn't aware of the 64-character limit for values in config.json. So I shortened all the values and then tried to upload again, and now I get this error each time:
![screen shot 2018-06-05 at 10 44 42 am](https://user-images.githubusercontent.com/12576940/40983723-3bc49456-68ae-11e8-9852-a477cbbaebdd.png)

I noticed that the the TR-4400 code can mean that string lengths are too long in other JSON files besides config.json--does the 64-character limit apply to all JSON files inside a theme?

**Comment by junedkazi** [comment]
@dunxtand it should be specific to `config.json`

**Comment by dunxtand** [comment]
@junedkazi Okay. Any thoughts on the error message that I got once I cleared up the first one?

**Comment by brandonjp** [comment]
@dunxtand Any update on if/how you got passed this issue?  I'm having the same trouble and so far just running into broken docs links and 'not sure' from BigCommerce support :/
