### ISSUE TITLE
Upgrade stencil-cli to handlebars v4

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#402]
Are there any plans to update the version of handlebars that stencil-cli uses? In v4, handlebars made changes to how context changes with certain block helpers.

I'm using handlebars on the client-side, and it's nice to be able to share templates between the client and server. However, using v4 on the client causes issues since the number of `../` uses within blocks needs to be different for v3 on the sever, and v4 on the client.

See "Compatibility notes" here: https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v400---september-1st-2015

And https://github.com/wycats/handlebars.js/issues/1028

**Comment by diztinct-glenn** [comment]
I reckon this can be marked closed now, no?

**Comment by dannydulai** [comment]
how does one enable v4?
