### ISSUE TITLE
`stencil push` and `stencil bundle`-generated .zip file resulting in TR-300 error

### ISSUE THREAD

**Issue by dluks** [bigcommerce/stencil-cli#403]
### Expected behavior
No error; no apparent issues with the theme.

### Actual behavior
`stencil push` results in a `JobCompletionStatusCheckError: Job Failed`, usually with 0% processing, sometimes with 12%.

Manual upload of .zip file to BigCommerce reveals a `TR-300` error. No `bundle.js.map` file is present, and so further debugging becomes a bit mystifying.

.zip file produced by `stencil bundle` is 31.4 MB.

### Steps to reproduce behavior
Any other suggestions on what might trigger a `TR-300`?

**Comment by dluks** [comment]
Turns out I had a jpeg in `/img/` that was 21.4 MB. I resized it to ~300 KB and the issue was resolved. Regardless, I was unable to find anything in the Stencil docs addressing this issue aside from the strict 50 MB limit. Does anybody know why this might occur?

**Comment by junedkazi** [comment]
This should be addressed as part of https://github.com/bigcommerce/stencil-cli/pull/405 and https://github.com/bigcommerce/stencil-cli/pull/413. Plese re-open if it is still an issue.

**Comment by steve-ross** [comment]
Also, saw this same issue if you have large bundle.js (ie: development mode) that doesn't get cleaned up... would be nice to know the offending files.
