### ISSUE TITLE
SASS import file not found when using nested relative imports

### ISSUE THREAD

**Issue by steve-ross** [bigcommerce/stencil-cli#404]
### Expected behavior
The file is imported as it does actually exist 🙂

### Actual behavior
Random failures (hitting refresh a few times will fix it at random)
```
{ Error: ./header.scss doesn't exist!
    at options.error (/Users/homedir/.nvm/versions/node/v8.11.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/lib/index.js:277:32)
  formatted: 'Error: ./header.scss doesn\'t exist!\n        on line 2 of stdin\n>> @import \'./header\';\n   --------^\n',
  message: './header.scss doesn\'t exist!',
  column: 9,
  line: 2,
  file: 'stdin',
  status: 1 }
```

### Steps to reproduce behavior

I haven't tried this on cornerstone or a new theme but, in ours we have some nested imports where the main theme file will import `header` and `header.scss` imports all of the files in the `./header`:
![image](https://user-images.githubusercontent.com/297351/43645137-095c4bec-96ff-11e8-8fff-eae9b0c71898.png)

sample base theme file that is doing the nested imports:

```
@import './variables';
@import './header';
```

The strangest part is this just randomly works or fails. Tried moving up and down on node versions and tried moving all the imports to the main theme file and the issue comes back.

I did dig up this issue: https://github.com/sass/libsass/issues/1750  so it did make me wonder if the version of hode-sass needed to be updated in stencil-cli.

**Comment by canterberrygifts** [comment]
This seems be an issue in the windows environment  [#387](https://github.com/bigcommerce/stencil-cli/issues/387)

{ Error: bootstrap\variables.scss doesn't exist!
at options.error (C:\Users\matth\AppData\Roaming\npm\node_modules@bigcommerce\stencil-cli\node_modules@bigcommerce\node-sass\lib\index.js:277:32)

I would love a solution.  The work around he used didn't work for me.  

**My environment** 
OS: Windows 10
git 2.19.1
Python 2.7
Node 8.12.0
MS Visual Studio 2017
Theme: Blackdeers V 1.0.1

**Comment by mikemfleming** [comment]
I'm getting the same error as this issue and https://github.com/sass/libsass/issues/1750 only I am in a Mac environment.

**Comment by steve-ross** [comment]
FWIW an odd fix on our theme (a modification of peak) was to import the main 'theme.scss' in our override file first and then proceed with our own imports. Haven't seen the error come back.
