### ISSUE TITLE
Stencil Push results in parsing error

### ISSUE THREAD

**Issue by creativecjh** [bigcommerce/stencil-cli#408]
### Expected behavior
`stencil push`  successfully uploads local theme files to online store.

### Actual behavior
`stencil push` and `stencil bundle` result in parsing error as pictured.

![image](https://user-images.githubusercontent.com/13133604/44234520-c9e05280-a174-11e8-9820-1b50476b55be.png)

### Steps to reproduce behavior
I'm using a stencil based marketplace theme, LaParis 1.0.13.

**Comment by karen-white** [comment]
@creativecjh It looks like a syntax error coming from your lightbox dependency. If you'd like, you can email your theme files to karen.white@bigcommerce.com and I'll take a look

**Comment by junedkazi** [comment]
@creativecjh @karen-white I am hoping this issue is resolved. If it is still an issue due to stencil cli please re-open this issue.
