### ISSUE TITLE
Error: Command failed: git config --get remote.origin.url 

### ISSUE THREAD

**Issue by sseoussama** [bigcommerce/stencil-cli#411]
i got that error while installing stencil-cli 
node : 6.9.0 
git : 2.18.0

![capture d ecran 2018-09-05 a 20 54 47](https://user-images.githubusercontent.com/30413494/45119407-4e5e3980-b153-11e8-864f-423163b0eff8.png)

**Comment by junedkazi** [comment]
This is over 6 months old so I am going to close it. I would recommend you please try the latest 3.x version and please open a new issue if you run into any issues.
