### ISSUE TITLE
NPM Install ERROR (Node v10.6.0)

### ISSUE THREAD

**Issue by ashussen** [bigcommerce/stencil-cli#417]
### Expected behavior
I tried to do `npm install -g @bigcommerce/stencil-cli`
But this turns out to be a long error message (see below)

### Actual behavior
```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/albert/.node-gyp/10.6.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/albert/.node-gyp/10.6.0/include/node -I/Users/albert/.node-gyp/10.6.0/src -I/Users/albert/.node-gyp/10.6.0/deps/openssl/config -I/Users/albert/.node-gyp/10.6.0/deps/openssl/openssl/include -I/Users/albert/.node-gyp/10.6.0/deps/uv/include -I/Users/albert/.node-gyp/10.6.0/deps/zlib -I/Users/albert/.node-gyp/10.6.0/deps/v8/include -I../../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-threadsafe-statics -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/10.6.0/bin/node" "/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bigcommerce/node-sass@3.4.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @bigcommerce/node-sass@3.4.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/albert/.npm/_logs/2018-10-22T07_02_07_953Z-debug.log
```

### Steps to reproduce behavior
Mac OSX High Sierra
Node v10.6.0
NPM 6.4.1

**Comment by ONeill45** [comment]
I received the same error 

Mac OS High Sierra 10.13.6
Node v10.11.0
NPM 6.4.1

**Comment by ashussen** [comment]
@ONeill45 
I end up downgrading my Node version with `nvm`, then install stencil again.
Everything works smoothly from after that.

Reference: [NVM](https://github.com/creationix/nvm)

**Comment by slater101** [comment]
What version works then? I just installed 9.9.0 and same issue here. 

There needs to be mention of the proper versions etc on the website at https://developer.bigcommerce.com/stencil-docs/getting-started/installing-stencil

**Comment by ashussen** [comment]
> Note: Stencil requires the Node.js runtime environment, version 6.x or later. We have tested Stencil on selected Node.js versions, from 6.10.3 to 8.12.0

That is the first line in the documentation. They didn't say it clearly that it only works on version 8.12.0 max.

**Comment by slater101** [comment]
Yea, I didn't see that, my bad, although many of my links that where bookmarked for Bigcommerce are now broken so I was lost on my key notes lol.

Up and running now though :-) :+1:

**Comment by cory-arcticleaf** [comment]
Does anyone know if there is any plan to support Node v10 in the future as it is now the latest LTS?

**Comment by matt-bailey** [comment]
This is still an issue, took me a while to figure out what was going on...

**Comment by carsonreinke** [comment]
See https://github.com/bigcommerce-labs/node-sass/pull/5

**Comment by jsimm-guidance** [comment]
same issue 
Microsoft Windows [Version 10.0.17763.316] x64
used nvm for windows to downgrade to node 8.12.0

**Comment by LordZardeck** [comment]
Please update your supported engines in NPM then so that users are made aware of this. 

https://docs.npmjs.com/files/package.json#engines 

https://github.com/bigcommerce/stencil-cli/blob/master/package.json#L6

**Comment by junedkazi** [comment]
Please use the latest version of stencil-cli which should support node 10. We are also working on adding support for node 12 soon. Please open a new issue if you run into any issues with the latest cli version on node 10.
