### ISSUE TITLE
Add flag to auto-delete oldest Theme when pushing

### ISSUE THREAD

**Issue by nowlena** [bigcommerce/stencil-cli#429]
For some larger clients we are auto-deploying to various stores (_almost_) without a problem

# the Issue

When a store has too many Themes uploaded our deployment cannot apply the Theme because we are instead prompted to choose which Themes to delete.

# the solution / request

Essentially we want a flag that will automatically delete the oldest Theme so that our ours can be applied

Ideally we could do something like `stencil push --activate --force` or `stencil push --activate true`

Please let me know if further clarification is needed.

**Comment by Plonq** [comment]
Yep, would love this. Tried automating the theme deletion prompt with `expect` without success.

**Comment by mikemfleming** [comment]
I'm on the same page using a CircleCI build, I haven't found a good way around this problem (ie - nothing that doesn't involve a lot of bash scripting). 

Something similar was done in #380 and a gap in the documentation was noted here #432 as well. 

Our build fails when encountering the below prompt.

<img width="1528" alt="screen shot 2019-01-16 at 11 38 15 am" src="https://user-images.githubusercontent.com/14914451/51274878-f1428200-1995-11e9-8aa0-0d3737f5c9f6.png">

**Comment by Plonq** [comment]
For what it's worth, I was able to finally get it working using `expect` with the below script

`#!/usr/bin/expect

spawn ./node_modules/.bin/stencil push -a THEME_VARIATION
expect -re "Zipping Files Finished"
send " \r"
interact`

**Comment by mikemfleming** [comment]
I agree, it's something that should be supported with a flag. I also just got mine working with a script that deletes themes using the API. It's hacky but it will work until a better solution comes along.

```js
const axios = require('axios');

const {
    API_URL,
    BC_CLIENT_ID,
    BC_ACCESS_TOKEN,
} = process.env;

const getAllThemesConfig = {
    method: 'get',
    url: `${API_URL}/themes`,
    headers: {
        'X-Auth-Client': BC_CLIENT_ID,
        'X-Auth-Token': BC_ACCESS_TOKEN,
    },
};

makeRequest(getAllThemesConfig).then((response) => {
    const ids = response.data && Array.isArray(response.data)
        ? response.data.filter(t => !t.is_active && t.is_private).map(t => t.uuid) // trying to filter out the theme we forked and our active theme
        : false;

    if (ids) return ids;

    throw new Error('MALFORMED BC API RESPONSE - NO THEME UUID\'S PRESENT');
}).then(deleteAllThemes)
.catch(e => console.log('ERROR GETTING THEMES', e));

function makeRequest(config) {
    return axios(config)
        .then(response => response.data)
        .catch(({ response }) => { throw response.data; });
}

function deleteThemeRequest(themeId) {
    const deleteThemeConfig = {
        method: 'delete',
        url: `${API_URL}/themes/${themeId}`,
        headers: {
            'X-Auth-Client': BC_CLIENT_ID,
            'X-Auth-Token': BC_ACCESS_TOKEN,
        },
    };

    return makeRequest(deleteThemeConfig)
        .then(() => console.log('DELETED THEME'))
        .catch(e => console.log('ERROR DELETING THEMES', JSON.stringify(e, null, 4)));
}

function deleteAllThemes (ids) {
    return Promise.all(ids.map(deleteThemeRequest));
}

```

**Comment by garnerp** [comment]
Is it possible to put the theme version or maybe the pushed date into the API response to facilitate an automatic delete from CI?

**Comment by obrien-k** [comment]
Hey @nowlena #548 added a flag to give an option for deleting the oldest theme during a push, can you confirm this is resolved?

**Comment by junedkazi** [comment]
Going to close this since it has been resolved.
