### ISSUE TITLE
Stencil CLI push not working

### ISSUE THREAD

**Issue by coreyshaw** [bigcommerce/stencil-cli#434]
I started creating a theme off of the cornerstone theme. The theme works perfectly when running it with stencil start. However when I go to run stencil bundle and then stencil push I get the following error.

```
Validating theme...
Running ESLint...

SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
ok -- Theme task Finished
Generating Manifest Started...
ok -- Manifest Generation Finished
ok -- Zipping Files Finished


not ok -- ThemeUploadError: Server Error see details below:
unknown error
If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
```

I am unsure what the problem is since there are no error messages. I then tried uploading the theme through the UI and I also get an error.

```
{eventName: "ATHENA_EVENTS.PRIVATE_THEME_PROCESSING_FAILED",…}
eventName: "ATHENA_EVENTS.PRIVATE_THEME_PROCESSING_FAILED"
options: {producerFlow: "storefront manager", producerSource: "BIGCOMMERCE CONTROL PANEL"}
producerFlow: "storefront manager"
producerSource: "BIGCOMMERCE CONTROL PANEL"
payload: {fileName: "Wheellab-1.0.0.zip", jobId: "6603a685eefa7d9bcb57eb81e23a7ec6",…}
fileName: "Wheellab-1.0.0.zip"
jobId: "6603a685eefa7d9bcb57eb81e23a7ec6"
message: "[{"error":"tr_300","message":"There was a problem with the zip file. (TR-300)"}]"
```

I am using the OAuth credentials for this also. The scopes for stencil CLI are:

```
Themes, Content Read-Only, Products Read-Only
```

The store is also in maintenance mode.

Here is also a link to my new themes repo if that helps at all.

https://gitlab.com/wheellab/wheellab-bigcommerce

**Comment by karen-white** [comment]
Thanks for reporting this @coreyshaw ! I'll put in an internal ticket to address it.

**Comment by coreyshaw** [comment]
Thanks! Do you have any idea when this might be resolved and ready to test? This is currently a blocker for us for getting our new theme out.

Thanks again!

**Comment by coreyshaw** [comment]
@karen-white what exactly do you mean by max of 5mb do you mean the templates directory inside of my theme? If so my templates directory is 434kb. My entire template with all the files is 238mb but I haven't changed much from the base cornerstone theme. Can you try bundling and uploading my theme to a test site to see if it works for you? https://gitlab.com/wheellab/wheellab-bigcommerce

Honestly if the stencil push works I don't care as much about the manual upload.

Thanks

**Comment by karen-white** [comment]
@coreyshaw Apologies, should have clarified! In addition to the total max bundle size of 50MB, 5MB is the max for any single file within the bundle, and 1MB is the max for either the /templates/ or the /parsed/templates directories within the bundle. The max unzipped file size is 100MB and there's also a limit of less than 2500 total files.

When I try bundling and uploading your theme, I get the same TR-300 error on upload that you were seeing, indicating a file size issue:

`{"data":{"themeCopy":[],"privateTheme":[{"id":"ef8c0a873fcfbf200818e83a9810b65b","time":"2018-12-31T23:04:14+00:00","status":"failed","percentComplete":12,"errors":[{"error":"tr_300","message":"There was a problem with the zip file. (TR-300)"}]}],"downloadProcessing":[],"editTheme":[]},"meta":{}}`

Once the `stencil push` issue is resolved, this theme would still not upload as-is. It would take some troubleshooting to determine what's exceeding the size limits within your theme.

**Comment by coreyshaw** [comment]
Interesting I don’t understand what could be causing it to be so large, all I have changed is html and sass files from what I can remember. So the entire theme needs to be less then 100mb?

**Comment by coreyshaw** [comment]
@karen-white when you say total bundle size do you mean the total size of the bundled zip file that is output?

**Comment by coreyshaw** [comment]
@karen-white I figured out why the theme wasn't uploading via the UI, thanks for that information! Please let me know when the stencil push issue is fixed.

Also do you know if anyone has hooked the stencil push functionality into a CICD pipeline? I noticed there is a .travis file.

Thanks

**Comment by bookernath** [comment]
@coreyshaw this should be working via CLI now. Can you test it?

**Comment by coreyshaw** [comment]
Looks like its working now thanks. Do you know if folks have integrated this with CICD?

**Comment by karen-white** [comment]
@coreyshaw Glad you were able to get the UI upload working! Thanks again for letting us know about the CLI issue.

Travis is what we use internally, but I have seen external devs use Stencil push to hook into a CICD pipeline, most commonly with Bitbucket. You can run `stencil push` with an optional -a flag to automatically apply a theme variation without the CLI command prompt asking you which variation you want to apply, which allows you to script the command in your CD pipeline. For example, `stencil push -a light`. 

I have a blog post coming out in February about integrating CICD with Stencil, so stay tuned!

**Comment by coreyshaw** [comment]
@karen-white Thanks! Do you know if you have any examples of this?

**Comment by coreyshaw** [comment]
Also is there a way for the stencil push to just apply updates to the theme and not make an entirely new theme?

**Comment by karen-white** [comment]
Want to send me an email at karen.white@bigcommerce.com so we can connect offline? I can take you through a few examples of pipeline architecture when we get back into the office on Wednesday.

And for updating rather than making an entirely new theme, it's not possible to overwrite the existing theme. You can however write a script to check how many themes are currently uploaded to the store, and if you're at the max, delete the oldest.

**Comment by coreyshaw** [comment]
Makes sense, I sent you over the email. Should see it shortly its from corey@wheellab.us

**Comment by bookernath** [comment]
@coreyshaw if your immediate issue around push is fixed, would you mind closing this issue?

Thank you, and happy new year!

**Comment by bookernath** [comment]
@coreyshaw if your immediate issue around push is fixed, would you mind closing this issue?

Thank you, and happy new year!

**Comment by coreyshaw** [comment]
Will do thanks!
