### ISSUE TITLE
win10  stencil-cli  install  not success

### ISSUE THREAD

**Issue by wangxingxing123654** [bigcommerce/stencil-cli#456]
### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/28847126/57177325-a2155400-6e95-11e9-9158-0d5174ad67d4.png)
node version is 7.9.0,and stop at the scene like the upper photo,how can i change this

**Comment by karen-white** [comment]
Can you confirm the installation steps that you take before this point and that all of the [Windows-specific dependencies](https://developer.bigcommerce.com/stencil-docs/getting-started/installing-stencil#installing_prerequisites-4) have been installed?

**Comment by junedkazi** [comment]
I am going to close this one since we no longer support node 7. Can you please try the latest cli version with node 10. If you are still experiencing this issue please feel free to open a new issue.
