### ISSUE TITLE
unable to find any out put file in build using this command stencil push -a light

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#457]
**###** Expected behavior
i tried this command **stencil push -a light** in yml file for build (build was successed) but unable to find any out put file(zip file) please help me on this

**Comment by karen-white** [comment]
Hey @mahammad13 , `stencil push` will automatically upload the theme bundle to your store. You can run `stencil bundle` if you want to generate the zip file and upload it manually.

**Comment by mahammad13** [comment]
Hi Karen..thanks for your inoformation
i want to automatically upload the theme using azure devops or yml file.
run the yml file script geting below error..
not ok -- ThemeUploadError: You can only upload one theme at a time see details below:
unknown error
If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
##[section]Finishing: Stencil Push

**Comment by mahammad13** [comment]
![stencil](https://user-images.githubusercontent.com/41624407/57318617-5e7e4c80-7118-11e9-970c-fcbfe067d5bb.png)

**Comment by karen-white** [comment]
@mahammad13 It sounds like a previously uploaded theme is still being processed. Do you still see that error after waiting for the previous upload job to finish?

**Comment by karen-white** [comment]
@mahammad13 Closing this out, but please feel free to reopen if you're still experiencing the issue.
