### ISSUE TITLE
how to upload zip file to bigcommerce (use stencil bundle)

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#458]
### Expected behavior
Running ESLint...

SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
ok -- Theme task Finished
Generating Manifest Started...
ok -- Manifest Generation Finished
ok -- Zipping Files Finished
Bundled saved to: /home/vsts/work/1/s/Cornerstone-3.4.0.zip

**Comment by karen-white** [comment]
@mahammad13 If you have the zip file after running `stencil bundle`, you can upload it via the control panel. Support article linked here (see Uploading a Custom Theme): https://support.bigcommerce.com/s/article/Stencil-Themes#download-upload

**Comment by karen-white** [comment]
@mahammad13 Following up to see if this answered your question. Please feel free to close this out if it's resolved. Thanks!

**Comment by junedkazi** [comment]
@mahammad13 I am guessing the issue is resolved. Please re-open this issue if you have more questions.
