### ISSUE TITLE
stencil push -a light using bash script in azure devops getting below error...

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#459]
TypeError: Cannot read property 'uuid' of undefined
    at themeApiClient.getVariationsByThemeId (/opt/hostedtoolcache/node/8.16.0/x64/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-push.utils.js:297:84)
please help me on this......
Thanks
Mahammad

**Comment by karen-white** [comment]
Hey @mahammad13 , we'll likely need more information to troubleshoot this issue. What commands are you running in your bash script?

You might also find this blog post helpful: https://medium.com/bigcommerce-developer-blog/how-to-level-up-your-development-workflow-with-continuous-delivery-3a6493cc1d13

**Comment by jeremysimmons** [comment]
@mahammad13 I believe the variation name is case sensitive

**Comment by mahammad13** [comment]
@ karen-white .......i have run stencil push -a light

**Comment by mahammad13** [comment]
@jeremysimmons :  Thanks jeremysimmons ...now its uploaded the themes (it seems variant id is case senstive)

**Comment by karen-white** [comment]
Thanks @jeremysimmons ! @mahammad13 , Closing this issue.
