### ISSUE TITLE
eslint requiring trailing comma on rest properties

### ISSUE THREAD

**Issue by atsheridan** [bigcommerce/stencil-cli#461]
`stencil bundle` is failing on projects that use Javascript rest properties, as eslint incorrectly expects a trailing comma after rest property (`Missing trailing comma`). This is a bug in eslint which was fixed in 3.8 (eslint/eslint#7297)
This behaviour is also inconsistent with cornerstone, which will actually (correctly) complain (`Unexpected trailing comma`) if the trailing comma _is_ included.

I fixed this locally by updating the eslint dependency to 3.8.1, but not sure if this introduces other bugs or side effects

### Expected behavior
Stencil bundle completes without error

### Actual behavior
Stencil bundle fails on eslint step if a rest property is encountered without a trailing comma.  `error Missing trailing comma comma-dangle`

### Steps to reproduce behavior
- Use a rest property in an active Javascript file (properties must span multiple lines), e.g.
```
export default class SomeClass {
    constructor({
        a,
        b,
        ...rest // This line will error
    } = {}) {
        this.c = { ...rest };
    }
}
```
- Execute `stencil bundle`

**Comment by junedkazi** [comment]
This should be fixed as part of 1.23.0 release. See https://github.com/bigcommerce/stencil-cli/blob/master/CHANGELOG.md#1230-2020-02-17 for more details. Please do open a new issue if the issue still persists.
