### ISSUE TITLE
i have build & release pipeline for themes upload(.stencil file) using the devops(azure devops)getting below error

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#462]
not ok -- StencilConfigReadError: ENOENT: no such file or directory, open './.stencil'

Please help me on this....

**Comment by karen-white** [comment]
@mahammad13 I was able to replicate this error if I ran a pipeline build without a .stencil file in my working directory. Could you confirm that your .stencil file is present? Thanks!

**Comment by mahammad13** [comment]
yes..karen-white .stencil file is there.....

**Comment by mahammad13** [comment]
Hi Karen-white
now i am getting below error while build the pipeline
;
TypeError: Cannot read property 'filter' of undefined
2019-05-13T11:15:20.3147638Z     at Fs.readdir (/opt/hostedtoolcache/node/8.16.0/x64/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-bundle.js:113:39)
2019-05-13T11:15:20.3147700Z     at FSReqWrap.oncomplete (fs.js:135:15)

Please help me...

**Comment by karen-white** [comment]
Closing as duplicate of #464
