### ISSUE TITLE
i have created azure build & release but how can i release same .stencil (theme) to staging & testing environments? 

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#463]
how can i release the  same .stencil (theme) to staging & testing environments? 
2  different environments(url's are different s)

**Comment by karen-white** [comment]
@mahammad13 You'll need separate .stencil files for each environment. You could do something like put your .stencil files in their own directories and copy the correct file to the working directory in your bash script at runtime. If you're using a particular naming convention to organize your .stencil file directories, you could use [pipeline variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) to select the directory for the proper credentials.

**Comment by mahammad13** [comment]
Hi Karen...i am new to big commerce ..could you please elaborate more on this issue..(we have 3 environments and we have single .stencil file) we want update .stencil file for every time for build(ex: dev ,test,prod).
In azure devops  1)we have a single build(artifacts created) and we have to move(release) to dev ,test and prod( once the pre deployment approvals are done)

please help me on this issue..
Thanks,
Mahammad

**Comment by karen-white** [comment]
@mahammad13 If each of those environments is a separate BigCommerce store instance, each environment will need its own .stencil file that points to the URL and API credentials for that particular store. 

If you're running a 3 stage deployment that deploys to 3 different BigCommerce instances, within each stage, you could copy the correct .stencil file into the current working directory and then clean it up after the build finishes. For example:

`cp /credentials/dev/.stencil .`
`stencil push -a Light`
`rm .stencil`

**Comment by mahammad13** [comment]
Hi Karen..Thanks for your inputs (solution)..
we have implemented this in other way ..
ex: we have 3 environments right and we create 3 stencil files and renaming to that files in the directory like below. 
mv  -f  .stencil test  .stencil
stencil push -a light
mv  -f  .stencil  .stencil test..
----------------------------
i will try to this way as well which you mentioned above ..update you ..

**Comment by junedkazi** [comment]
Since this is not a stencil-cli issue & the author has found a work around I am going to go ahead and close this issue.
