### ISSUE TITLE
The URLs in a html page are parameterized like the following - urls.auth.check_login. Is there any environment specific setting to change this?

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#477]
The URLs in a html page are parameterized like the following - urls.auth.check_login. Is there any environment specific setting to change this?
please help me on this issue?

Thanks,
Mahammad

**Comment by junedkazi** [comment]
@mahammad13 you haven't specified what are you trying to do ? What is wrong with the existing format and what format you want to see the urls list in ?

**Comment by junedkazi** [comment]
No update from the author @mahammad13  so I am going to go ahead and close the issue assuming you have figured out how to work around it or with it.
