### ISSUE TITLE
how to remove cornerstone themes from big commerce(it allow 19 themes only) after i can not push the themes  to big-commerce

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#483]
getting below issue:
![image](https://user-images.githubusercontent.com/41624407/59504739-388b5b00-8ec1-11e9-840a-77d53197a5ac.png)

Please help me on this issue..

**Comment by mahammad13** [comment]
how to remove themes automatically from big-commerce.?

**Comment by karen-white** [comment]
@mahammad13 If you want to programmatically remove a theme, you'll want to write a script that runs during your pipeline (before stencil push) to detect how many themes are in the store and delete one if you're getting close to the max of 20. We have a [themes API](https://developer.bigcommerce.com/api-reference/storefront/themes-api) you can use to get and delete themes. I'd also recommend this [Node API client](https://github.com/getconversio/node-bigcommerce) for handling API auth and requests in your script.

**Comment by mahammad13** [comment]
Thanks karen..
Is there any way to delete through command line?
i have tried few things by using the cmd line before stencil push(it won't work)
Ex: 
stencil push --activate --force or stencil push --activate true
could you please provide the your suggestions..

Thanks,
Mahammad

**Comment by karen-white** [comment]
@mahammad13 To confirm, there is not currently a command to delete a theme, so a script would be your best bet. PRs are welcome on this project though, if a --force flag is something you're interested in building out.

**Comment by mahammad13** [comment]
okay thanks for your input karen....
do you have any script or document related this issue ? if yes please share that ..it would be more help full for me..
Thanks,
Mahammad

**Comment by karen-white** [comment]
@mahammad13 I don't have an existing script, although we can definitely add that idea to our content planning. It would be a good tutorial idea for a blog post. In the meantime, if you come up with a script that you think would benefit the wider community and would like to publish it, let me know. We're always looking for guest contributors to our developer blog and we'd love to help give your work wider reach.

**Comment by bookernath** [comment]
When you see that screen in the CLI (the one in your screenshot), you can use the space bar and arrow keys to select a few existing themes to delete, and then click enter. The CLI will delete those themes and then upload your new one.

**Comment by karen-white** [comment]
@mahammad13 Should add that my answer was based on the assumption that you are running this as part of an automated deployment--if you are not running the command as part of a CD pipeline, then using the arrow keys to navigate in your terminal would be your best bet as @bookernath suggested :)

**Comment by scottfwebdev** [comment]
@karen-white How can the node-bigcommerce package be leveraged to run a script in a pipeline step before stencil push? Would that package need to be installed during the pipeline build, or would it need to be installed in the source code build of a BigCommerce Stencil project?

If that package needs to be installed during the pipeline build, how can the necessary auth credentials & associated script be loaded into the YAML file? (using a BitBucket pipeline)

**Comment by karen-white** [comment]
@scottfwebdev I'd approach it by including the script within your Bitbucket repository and running it as a build step in your pipeline:

node cleanup.js

You can install the node-bigcommerce package with your other project dependencies by running npm install as part of your pipeline (or if you'd prefer, you can just place the package in your project directory and forego installing it with every build).

**Comment by scottfwebdev** [comment]
@karen-white Thank you! I have that set up in my pipeline, and the GET request is successful to log the JSON data of the themes.

However, it seems that the only thing I am able to log in the console for testing purposes is _all_ of the data - attempting to log the data of just one item in the JSON array.

Works: `console.log(data);`
Does not work: `console.log(data[0]);`

Am I missing something, or am I targeting the wrong object? Without being able to access specific JSON items, I do not see how one would be able to then delete a theme based on the `uuid`.

**Comment by karen-white** [comment]
Hey @scottfwebdev , here's an example that might help. This is a bare-bones node http request to get the UUID of the first theme (this script isn't using the node-bigcommerce library but hopefully helps to illustrate how you can work with the API response)

```
#! /usr/bin/env node

const http = require("https");

const config = {
  "method": "GET",
  "hostname": "api.bigcommerce.com",
  "path": "/stores/{store-hash}/v3/themes",
  "headers": {
    "x-auth-client": "CLIENT_ID",
    "x-auth-token": "TOKEN",
    "accept": "application/json",
    "content-type": "application/json"
   }
};

const req = http.request(config, res => {

	let body = "";

  res.on('data', data => {
    body += data.toString();
  });

  res.on('end', () => {
    const themes = JSON.parse(body);
    console.log(themes.data[0].uuid);
  });
});

req.end();
```

**Comment by mahammad13** [comment]
Hi Karen,
Could you please provide the detail information about delete theme files from Bigc(19 exceed).
1. how to use above js script in Build & release pipeline for azure devops?
2. where to use above java script (js script)& how to configure to azure devops or build pipeline?
Please help me on this issue.
Thanks,
Mahammad Gouse

**Comment by karen-white** [comment]
Hi Mahammad, I think it's a great idea for our developer blog. I've got a post coming up on adding some testing and other utilities to a CD pipeline (scheduled for September) and I think this would be a useful section to add. The tutorial will probably use Bitbucket as the example, but the concepts should transfer over to Azure. I'm not sure I'll have the bandwidth to do the tutorial before then, but if I do, I'll share my code.

**Comment by scottfwebdev** [comment]
@karen-white I finally have my pipeline setup successfully functioning. Thank you for your help in here, and for the initial help you gave in your Developer Blog article!

@mahammad13 Apologies for hijacking your thread. While I do not have any experience with Azure, I have my pipeline set up in BitBucket using the node-bigcommerce package. Let me know if you have questions, and I may be able to help.

**Comment by mahammad13** [comment]
Hi Scott,
no-problem.. I need your help ..
1.How to use particular script in build (is there any task)?
2.Could you please elaborate more on this issue.
3.How to get UUID for theme?
4. Do you have document regarding this? 
actually i have tested API in postman  but not getting any result.
Please help me on this
Thanks,
Mahammad

**Comment by mahammad13** [comment]
@karen-white : 
How to use this js script in git repository and currently am using git repository versing tool and how to use in build pipeline?
we have set up build using git repository , could you please help me on this

Thanks,
Mahammad

**Comment by scottfwebdev** [comment]
@mahammad13 If you have not already read through Karen's article, check it out: https://medium.com/bigcommerce-developer-blog/how-to-level-up-your-development-workflow-with-continuous-delivery-3a6493cc1d13

1 & 2. When you have a pipeline set up (I am using BitBucket for this, tied to my repo), the YAML installs npm, installs stencil-cli, then runs a custom script to handle the theme GET & DELETE, then the stencil push command (ensure you use `stencil push -a [variant]` if you need to specify which theme variant to use).

One helpful part of Karen's article is to set up the Docker image to install npm, and stencil-cli outside of the pipeline's YAML config file - definitely look into that.

My custom script resides within the main directory of my project, but you could use other methods of how to set it up. This is where #3 comes in...

3. To get the UUID, install the node-bigcommerce package, and check out the README for it. I had some trouble with this at first, but ultimately got it to work. When you have all of your API credentials in place (clientid, token, store hash, etc.), use the `bigCommerce.get` method to get the data of the object it returns, then if you want to check if there are more than 19 themes, a simple if statement to then call the bigCommerce.delete method based on a variable in the /themes/ path for the specific theme UUID you want to remove.

4. As far as documentation, I actually found little information specific to this kind of task. It was mostly all thanks to Karen's article, and her assistance in this thread that led me to success on this.

Good luck, and I am happy to try to help if you run into any walls.

**Comment by mahammad13** [comment]
Hi Scott..
sorry for the late response..
I hope your explained clearly but i am not sure how to do implement this one in build.
Please help me on this..
we have API & i have hit that API in postman getting below things.


"UUID": "xxxxx"
"name": "theme"
            "is_private": true,
            "is_active": true

 how to delete themes from environment.?

 We have some script in below but how to use this one in build.

function deleteThemeById(options, callback) {
    Wreck.delete(`${options.apiHost}/stores/${options.storeHash}/v3/themes/${options.themeId}`, {
        headers: {
            'x-auth-client': options.clientId,
            'x-auth-token': options.accessToken,
        },
        json: true,
    }, err => {
        if (err) {
            return callback(err);
        }

        callback(null);
    });
}

Please help me on this..

Thanks,
Mahammad

**Comment by scottfwebdev** [comment]
@mahammad13 I am using the [node-bigcommerce](https://github.com/getconversio/node-bigcommerce) package to handle the calls to the BigCommerce Themes API.

This is the script in my cleanup file, which is triggered during the pipeline build:

bigCommerce.get('/themes')
    .then(data => {
        let themes = data;
        let themeToDelete = themes.data[2].uuid;

        if (themes.data.length > 19) {
            console.log('There are more than 19 themes');

            bigCommerce.delete('/themes/' + themeToDelete)
                .then(() => {
                    console.log(`Theme UUID ${themeToDelete} has been deleted`);
                })
                .catch(err => {
                    console.error(err)
                });
        }
    })
    .catch(err => {
        console.error(err)
    });

The README for node-bigcommerce will show you how to initialize the calls in a variable with API credentials.

**Comment by karen-white** [comment]
Hey @mahammad13 - Wanted to let you know that the blog post is now live:
https://medium.com/bigcommerce-developer-blog/cd-pipelines-part-2-how-to-add-performance-testing-and-utility-scripts-79238dac47e8?sk=0d7c57bb4ab51fd471c1310acde1c5fe

@scottfwebdev - thanks for sharing your example! I referenced it in my blog post--let me know if there's anything specific you'd like me to cite in the attribution!

**Comment by scottfwebdev** [comment]
@karen-white Certainly! I may amend my script to incorporate the private vs. custom theme aspects, and I am very intrigued about adding the Lighthouse step in the pipeline. 

One other major hurdle I was able to get over, just a few hours prior to this writing, is setting up steps to manage variations in .stencil config files when dealing with different Git branches connected to sandbox, or production store environments. It was a pain to keep copying/pasting a different URL, and API credentials, so I set up a shell script to alter the .stencil config's values during the build process. It seems to be working well so far, though I have a bit more testing to do.

**Comment by karen-white** [comment]
That's awesome @scottfwebdev ! Sounds like a useful automation :)

@mahammad13 - I'm going to go ahead and close this out, but let us know if you have questions.

**Comment by mahammad13** [comment]
@karen-white - That's awesome....
Now my Build & release pipeline is working fine with your code..Thank you so much for your help.. Keep going..

Thanks,
Mahammad

**Comment by karen-white** [comment]
Yay, that's great @mahammad13 ! Glad to hear it :)

**Comment by mahammad13** [comment]
Hi karen-white,
We have 3 environments(ex:dev,stage,prod) and  i have add 3 .js files with clientid,accesstoken & storehash(i think hot coded values not secure) but how to hide or pass the values through variables in azure devops or other way.
Please provide your suggestion and comments.

Thanks,
Mahammad

**Comment by wutangpaul** [comment]
Hi @karen-white,
We're seeing the following error locally and in our CI environment when trying to access the themes API:
`{ Error: Request returned error code: 403 and body: $A
Hð^³ F® cvåMºL4ÎwoÚî>|ÞãN-ØªnxÜîWgÙf¸Á=y¥Äåb4
1Bl¡¤Ê¹k½~ùÉ¬êà}Â¹Ò¿òyY }ÔÜ%êGå2v­C
                                         éwüºÈ	Ú¤aiÇy~ÿÿÆC%°
    at IncomingMessage.res.on (/Users/xxx/Programming/xxx/node_modules/node-bigcommerce/lib/request.js:112:27)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 403,
  responseBody:
   '\u001f\b\u0000\u0000\u0000\u0000\u0000\u0000\u0000$A\n0\u0010E¯2dÓM5våMºL\u00064ÎwoÚî>|Þã\u001dN-ØªnxÜîWgÙf¸Á=y¥Äåb4\r\u0014Hð^³ F® c\n1Bl\u0002¡¤Ê¹k½~ùÉ¬êà}Â¹\u0001Ò¿ò\u0018yY \u0011}\u001b>ÔÜ%êGå2v­C\féwüºÈ\tÚ¤\u0010aiÇy~\u0000\u0000\u0000ÿÿ\u0003\u0000ÆC%°\u0000\u0000\u0000' }`

Any idea what could be cause this? We've followed the script exactly as per https://medium.com/bigcommerce-developer-blog/cd-pipelines-part-2-how-to-add-performance-testing-and-utility-scripts-79238dac47e8?sk=0d7c57bb4ab51fd471c1310acde1c5fe
