### ISSUE TITLE
Self hosted stencil templates

### ISSUE THREAD

**Issue by yjimk** [bigcommerce/stencil-cli#486]
Hi there,

Thanks for providing this library (and a really detailed set of docs), we’ve been using it for a client for around a year now and it’s been really neat.

The same client is currently in the process of changing their hosting policy and requiring projects to be bought in-house. In this case over to Google Cloud Platform.

Without getting into the specifics of GCP, is it possible to self host using this library? The dev server works well, but seems to be geared toward just that; dev. I could probably get the dev server working in a production environment, but worried about unintended consequences by doing so.

Thanks for your help!

**Comment by bookernath** [comment]
@yjimk stencil-cli is certainly NOT intended to serve production storefront traffic so we really can't vouch for it being used in that way I'm afraid.

We'd usually recommend a ["headless"](https://www.bigcommerce.com/solutions/commerce-as-a-service/) approach at that point

**Comment by yjimk** [comment]
Thanks @bookernath for the quick reply!

Looks like headless is the way to go then! I'll close this issue off now.
