### ISSUE TITLE
how to change the URL to corresponding environment for Dev, QA and Prod

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#487]
In the specified screen shot the token url(login.html) is point out to Dev environment and we need to change the URL to corresponding environment for QA and Prod(here Bigc, stencil code and only one login html file is there) but in java we use java properties file and changed accordingly(Dev,QA & Prod)

How to do this changes ?, we can do it manual changes in login html file for corresponding env **or** is there any way to change this one ,Please help me on this.

**below is the screenshot**

![image](https://user-images.githubusercontent.com/41624407/60024721-ebc03500-96b5-11e9-8f1e-0e85353834d1.png)

**Below is the token url(dev) in login.html** 

![image](https://user-images.githubusercontent.com/41624407/60026031-799d1f80-96b8-11e9-980e-3ebe83b617c9.png)

Thanks,
Mahammad

**Comment by karen-white** [comment]
@mahammad13 You might be better served by opening this issue with Azure, since this question isn't related to Stencil CLI. The Azure community will have a better sense of whether this is something you can do with a build task, or what the best approach would be.

**Comment by mahammad13** [comment]
Thanks karen for your help & suggestions ..

Thanks,
Mahammad
