### ISSUE TITLE
when i push the theme to big commerce, getting below web pack issue ..

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#494]
![image](https://user-images.githubusercontent.com/41624407/61111268-d06f6b00-a4a6-11e9-9d50-aad60083bb43.png)

Could you please help me on this issue

Thanks,
Mahammad

**Comment by karen-white** [comment]
@mahammad13 Can you confirm that you're on a supported Node version? (we recommend 8x)

**Comment by mahammad13** [comment]
Hi Karen,
The node version is 8.9.0 ...
Now i am getting 403 forbidden error karen...Please help me on this
Thanks,
Mahammad

**Comment by karen-white** [comment]
@mahammad13 In that case, I'll go ahead and close out this issue and we can continue the conversation on #495
