### ISSUE TITLE
How to get the category of the product using handler bars?

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#498]
![image](https://user-images.githubusercontent.com/41624407/62268273-f4422300-b44c-11e9-9846-13ef986a8dae.png)
See the highlighted categories.
Please help me on this

Thanks,
Mahammad

**Comment by karen-white** [comment]
Hey @mahammad13 , you can get the array of categories the product belongs to with `{{product.category}}`. This is available when you're on the product page. It looks like that property is missing from our Stencil Object Model docs--we'll get that updated. 

You can also see the properties that are accessible to Handlebars helpers using this query parameter at the end of your localhost URL: `?debug=bar`. This exposes the full page context so you can see what data you have available to work with.

**Comment by junedkazi** [comment]
Since this is a support request and not an issue with cli I would request you to open it as a question in the community https://support.bigcommerce.com/s/qa.
