### ISSUE TITLE
TR-300

### ISSUE THREAD

**Issue by kalwiggins** [bigcommerce/stencil-cli#510]
I'm trying to push a theme update (on a cornerstone 1.7 child theme) with stencil. If I push it with no changes, it will push successfully. if I put a custom file in like pages/custom/_filename.html and leave it empty, it will push. if I copy the page template into that file, it will no longer push. I've tried renaming the file, putting other content into it, deleting it and starting new.

Here's the error I get:

```
Generating Manifest Started...
ok -- Manifest Generation Finished
ok -- Zipping Files Finished
ok -- Theme Upload Finished
Processing [======                                              ] 12%; ETA: 9.5

not ok -- JobCompletionStatusCheckError: Job Failed see details below:
There was a problem with the zip file. (TR-300)
```

I am able to run the stencil bundle successfully, just not push.

I originally thought it might be an issue with the file content, which is why I ended up just pasting the page.html content into it as a test.

Can you guys shed a light on TR-300? Is there a way to get a more detailed log during a stencil push?

UPDATE:
On further testing, it seems that my theme bundles and pushes as long as I don't exceed exactly 18 custom page templates. I'm trying to add a 19th, basically. I've tested adding this many templates on base cornerstone and it doesn't have an issue. What might prevent a successful push due to template count?

**Comment by karen-white** [comment]
Hey @kalwiggins , it sounds like the restriction isn't with the number of custom page templates (you can have more than 18), but you might be hitting one of these other upload limits:

Max directory size: /templates/ and /parsed/templates/  1 MB
Max for any single file in the bundle: 5 MB
Zip size max: 50 MB
Unzipped size max: 100 MB
Total number of files: 2500

Let us know if that helps!

**Comment by junedkazi** [comment]
@kalwiggins We also have documentation around it https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/troubleshooting-your-setup#troubleshooting_tr-300

**Comment by junedkazi** [comment]
@kalwiggins I am going to close this one for now. Please open a new issue if you have any followup questions.
