### ISSUE TITLE
500 errors in cli when accessing API

### ISSUE THREAD

**Issue by minutiae** [bigcommerce/stencil-cli#514]
I am able to start stencil, but when I view a product page that makes a request to the API to get product option details or add to the cart, most all of the time it waits for around 60 seconds then I get this error on the CLI:

Debug: internal, implementation, error
    Error: Error: The BigCommerce server responded with a 500 error
    at /Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:134:20
...

Running OSX, tried removing node_modules, a fresh install of stencil cli, set up Ubuntu and saw the same results.

**Comment by minutiae** [comment]
For my theme I'm on the version 3.5.1 of cornerstone if that makes a difference.

**Comment by karen-white** [comment]
Thanks for reporting this @minutiae ! We're tracking the issue via engineering ticket STRF-7331. We'll keep you posted on the progress!

**Comment by colinchan89** [comment]
Experiencing the same issue. 

Using Stencil CLI v1.20.0 and Node v8.16.1

**Comment by shaunj** [comment]
In case it helps finding a solutions. I ran into the same problem yesterday. 

```
Debug: internal, implementation, error
    Error: Error: The BigCommerce server responded with a 500 error
    at C:\ProgramData\nvm\v8.16.0\node_modules\@bigcommerce\stencil-cli\server\plugins\renderer\renderer.module.js:45:31
    at C:\ProgramData\nvm\v8.16.0\node_modules\@bigcommerce\stencil-cli\server\plugins\renderer\renderer.module.js:134:20
    at finish (C:\ProgramData\nvm\v8.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\wreck\lib\index.js:249:20)
    at wrapped (C:\ProgramData\nvm\v8.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\wreck\node_modules\hoek\lib\index.js:879:20)
    at ClientRequest.onResponse (C:\ProgramData\nvm\v8.16.0\node_modules\@bigcommerce\stencil-cli\node_modules\wreck\lib\index.js:200:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
```


I uninstalled everything nvm/node, stencil, etc, reinstalled following https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil 

It still didn't work. I happened to try a different browser and it WORKED.

* Works on Firefox 69.0
* Works on Microsoft Edge 42.17134.1.0
* Not working on Google Chrome 77.0.3865.75

Currently running 
Windows 10
webpack@4.27.1
Stencil 1.20.2
Node v8.16.0
nvm 1.1.7

**Comment by junedkazi** [comment]
Please update to the latest version of cli 1.20.2 and the issue should be resolved.
