### ISSUE TITLE
Can't log into account in local development

### ISSUE THREAD

**Issue by flair-chris** [bigcommerce/stencil-cli#518]
### Expected behavior
After clicking login with correct email and Password to be taken to the account page

### Actual behavior
Get returned to the login page with http://localhost:3000/login.php?from=account.php%3Faction%3D in the address bar.

### Steps to reproduce behavior
Latest version of stencil-cli (had been manifesting with 1.17 too), node 8.10.0 or 8.16.1 along with current cornerstone theme (i have been trying different themes all with the same problem).
start stencil then go to account and try and log in to a store you already have an account for.

It will let me create a new account but not log into an existing account. It seems to work when uploaded to a store.

I have been trying to reinstall stencil use different versions of node but can't get this solved. 

Using Mac OS 10.14.6

**Comment by adaamcollins** [comment]
@flair-chris happy to hear that someone else is having this issue, we thought it was just us!

**Comment by junedkazi** [comment]
@flair-chris @adaamcollins this should be resolved.
