### ISSUE TITLE
Response Error: 403 Forbidden

### ISSUE THREAD

**Issue by tjmatter** [bigcommerce/stencil-cli#519]
### Expected behavior
When I run `stencil start` command, it gives me an error message. Please see below. If it's template related error message, I can understand. But it is giving me 403 Forbidden error message and error is somewhere.

### Actual behavior
This is actual error message.
```bash
Debug: internal, implementation, error
    Error: Error: Response Error: 403 Forbidden
    at /Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:45:31
    at /Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/server/plugins/renderer/renderer.module.js:219:28
    at read (/Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:590:24)
    at finish (/Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:374:20)
    at wrapped (/Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/node_modules/hoek/lib/index.js:879:20)
    at module.exports.internals.Recorder.onReaderFinish (/Users/username/.nvm/versions/node/v8.16.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/wreck/lib/index.js:449:16)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at module.exports.internals.Recorder.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:613:14)
```

### Steps to reproduce behavior
Run stencil start. I've tried to change node versions. But it's still same. you can see my node version from the above.
Thank you.

**Comment by flair-chris** [comment]
@tjmatter Are you using legacy API credentials? I found legacy API credentials no longer work with the latest versions of stencil-cli

**Comment by tjmatter** [comment]
@flair-chris I don't think so, The store created recently /around March 2019/. I looked this message - `Legacy API Accounts - This is a deprecated feature! As of July 2018, this feature is no longer available to new stores or stores who have never used it` which means I can't create legacy API credentials since this date right?
Thank you.

**Comment by flair-chris** [comment]
> @flair-chris I don't think so, The store created recently /around March 2019/. I looked this message - `Legacy API Accounts - This is a deprecated feature! As of July 2018, this feature is no longer available to new stores or stores who have never used it` which means I can't create legacy API credentials since this date right?
> Thank you.

Ah ok, we have a few older stores that i was still using legacy API's with. 

Generally the 403 means that the api credentials are wrong, i would double check your .stencil file that have them all correct and make sure it has access to all the correct parts of the store that you need.

**Comment by tjmatter** [comment]
Okay thank you, I will double check all my configurations. Stranger thing is it happens when I sign in as customer. If the customer is not logged in, it works fine.

**Comment by flair-chris** [comment]
> Okay thank you, I will double check all my configurations. Stranger thing is it happens when I sign in as customer. If the customer is not logged in, it works fine.
oh, your credentials don't have permission to access the customer, you will need to reissue some api credentials: https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/live-previewing-a-theme

**Comment by flair-chris** [comment]
> Okay thank you, I will double check all my configurations. Stranger thing is it happens when I sign in as customer. If the customer is not logged in, it works fine.

oh, your credentials don't have permission to access the customer, you will need to reissue some api credentials: https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/live-previewing-a-theme

**Comment by tjmatter** [comment]
> > Okay thank you, I will double check all my configurations. Stranger thing is it happens when I sign in as customer. If the customer is not logged in, it works fine.
> 
> oh, your credentials don't have permission to access the customer, you will need to reissue some api credentials: https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/live-previewing-a-theme

I agree with you. Let me try to create a new one. I appreciate it. Cheers!
