### ISSUE TITLE
Align ESLint with Cornerstone

### ISSUE THREAD

**Issue by carsonreinke** [bigcommerce/stencil-cli#521]
### Expected behavior

ESLint to rules to be the same running either `grunt eslint` or `stencil bundle` with fresh Cornerstone theme.

### Actual behavior

ESLint rules are actually different.  Stencil is using its own ESLint rule set provided by [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb)

### Steps to reproduce behavior

1. `git clone git@github.com:bigcommerce/cornerstone.git`
2. `grunt eslint`
3. `stencil bundle`

**Comment by junedkazi** [comment]
We have update cli to no longer lint themes. We want to leave it to the theme developer to run lint as part of their development process. In the future release we might support triggering off a npm lint command defined in their `package.json` and fail bundle process if there are issues.

**Comment by carsonreinke** [comment]
@junedkazi I think it is best to just to leave it without any forced automated testing.  Maybe introducing some hooks in the future to automatically launch a command like testing that is up to the theme builder.  You could even use a prefix for `npm run`, something like `npm run stencil-test`.  Just some ideas.
