### ISSUE TITLE
Fail to update / global install stencil cli

### ISSUE THREAD

**Issue by elvc** [bigcommerce/stencil-cli#526]
There was an update 3 hours ago. Did the recent release just break the stencil cli install?

### Expected behavior
Able to globally install stencil cli

### Actual behavior
Errors shown towards the end of the `npm install`:
```
npm ERR! Unexpected end of JSON input while parsing near '...-6.9.2.tgz","fileCoun'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elvc/.npm/_logs/2019-10-10T22_57_08_636Z-debug.log
```

### Steps to reproduce behavior
https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil
```
nvm use 8.16
npm install -g @bigcommerce/stencil-cli
```

**Comment by elvc** [comment]
@bc-williamkwon Do you see the same errors?

**Comment by bc-williamkwon** [comment]
I dont see any error messages on my end.

**Comment by junedkazi** [comment]
@elvc if you don’t mind can you paste a dump of your debug log file so we have more details about the error.

**Comment by elvc** [comment]
```

**Comment by bc-williamkwon** [comment]
This may not be an issue with CLI.  @elvc can you check this article: https://webappcodes.com.cp-27.webhostbox.net/unexpected-end-of-json-input-while-run-npm-install?  I did have to reinstall my node version in order to run stencil start for 1.20.3 though.

**Comment by elvc** [comment]
Thanks. That worked!
