### ISSUE TITLE
stencil-cli install fails at node-sass build

### ISSUE THREAD

**Issue by P4ulJC** [bigcommerce/stencil-cli#528]
### Expected behavior
npm install -g @bigcommerce/stencil-cli should install stencil

### Actual behavior
The install process fails with the following error: 

```
../src/sass_types/list.cpp:28:73: error: too few arguments to function ‘Sass_Value* sass_make_list(size_t, Sass_Separator, bool)’
     return *out = sass_make_list(length, comma ? SASS_COMMA : SASS_SPACE);
                                                                         ^
In file included from ../src/sass_types/value.h:5:0,
                 from ../src/sass_types/sass_value_wrapper.h:7,
                 from ../src/sass_types/list.h:5,
                 from ../src/sass_types/list.cpp:2:
/usr/include/sass/values.h:53:34: note: declared here
 ADDAPI union Sass_Value* ADDCALL sass_make_list    (size_t len, enum Sass_Separator sep, bool is_bracketed);
                                  ^
../src/sass_types/list.cpp:29:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make: *** [Release/obj.target/binding/src/sass_types/list.o] Error 1
make: Leaving directory `/home/paul/.nvm/versions/node/v10.16.3/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass/build'
```

I've been running stencil for a couple of years. Last night I was prompted to update. I attempted to update stencil-cli but have been unsuccessful in doing so after much time trying. I use NVM to manage node versions and have tried version 8.0 10.1 and 10.16.3 (and also 12.0.0). The BigCommerce docs recommend version 10.16: https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil

My setup details are: 

OS: Linux

npm -v
6.12.0

node -v
10.16.3

node-sass -v
node-sass	4.12.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]

Incidentally, I did previously install libsass after first receiving an error about the missing header file sass/context.h. I used the convenience script here to download and install libsass:  https://gist.github.com/edouard-lopez/503d40a5c1a49cf8ae87

The node-sass page states that Node 10 requires node-sass of version 4.9+. So I tried installing version 4.9.4:  `npm install -g node-sass@4.9.4` but still received the above error. 

The above error is mentioned here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903195 in relation to libsass-python though you'd think the issue that occurred in 2018 due to a change in the libsass api would be rectified over a year later.

I've tried everything I can think of but no joy so far.

**Comment by junedkazi** [comment]
@P4ulJC this issue has been created a while ago and I was wondering if you are still running into a similar issue with the latest cli.

**Comment by junedkazi** [comment]
I am going to close this issue for now. If you are still experiencing this issue please feel free to open a new issue.
