### ISSUE TITLE
Error trying to use --tunnel option

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#538]
### Expected behavior
`stencil start --tunnel` should start the server with a local tunnel url.

### Actual behavior
The local server starts but not local tunnel url is created. The command line continuously prints out the following error:
> tunnel server offline: certificate has expired, retry 1s

### Steps to reproduce behavior
MacOS version 10.15.1
Node Version: v8.16.1
Stencil version 1.21.2

**Comment by brandonjp** [comment]
Same here.  Anyone currently having success with the `--tunnel` flag?

**Comment by junedkazi** [comment]
This should be fixed as part of 1.23.0 release. See https://github.com/bigcommerce/stencil-cli/blob/master/CHANGELOG.md#1230-2020-02-17 for more details.

**Comment by flyingL123** [comment]
@junedkazi I'm currently seeing the error with 1.23.1. I'm running Node 10.16.3 on Ubuntu 18.04.3 (LTS) x64

![image](https://user-images.githubusercontent.com/2486712/74798257-49377080-529b-11ea-957a-085eb221cdae.png)
