### ISSUE TITLE
Stencil start with theme editor binds the theme editor to localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by kgillis-atmosol** [bigcommerce/stencil-cli#543]
### Expected behavior
When starting up stencil start --theme-editor, the theme editor is usable from outside the device the same way that browsersync is.

### Actual behavior
The theme editor is not usable from outside the device.

### Steps to reproduce behavior
Start up stencil with the theme editor, and look at the port bindings. It'll be 127.0.0.1:8181 for the theme editor, and :::3000/:::3002 for browsersync/node.

The reason I've hit this as a problem is because we are transitioning our development environments from being local to being in docker containers in preparation for being able to provide staging environments where non-developers can more easily test the theme changes (as opposed to using Customize in the admin panel after the theme has been uploaded). Our theme changes often include additions to the theme editor to allow the admins to manage our customizations, so being able to see the theme editor both as a developer using the docker set up locally, or as a non-developer testing that the customization works as expected, is necessary. Binding the theme editor to 0.0.0.0 instead of localhost will resolve the problem.

**Comment by kgillis-atmosol** [comment]
Actually, turns out the problem is more widespread than I thought. The theme editor itself is hardcoded to use localhost for all of its links as well, rendering it entirely unable to run from a docker container, which takes some much desired functionality away from us as we were planning to use docker containers to create a public staging server where our clients and our project managers could see and interact with our changes before publishing them to the live site, without having to use the Theme Customize route inside the Bigcommerce admin panel as it doesn't show all of the areas, and somethings has issues with some of our customizations (nested iframes don't always behave well, for example). Often our customizations add areas to the theme editor to allow the client to manage the customization without having to contact us for each and every change, so being able to have a staging server where multiple stencil projects are running from docker containers with working theme editors would have helped immensely.

Is there any plan for this on the road map for stencil-cli, to be able to specify a url other than localhost for the theme editor?

**Comment by junedkazi** [comment]
@kgillis-atmosol we plan on deprecating theme editor which is part of stencil-cli since it is no longer being used in production and has been replaced with a complete rewrite. See #573 for more details. The plan right now is to provide theme developer a validator tool #555 which allows developers to validate their `schema.json` and will need manual verification on part of the theme developer to upload the theme to the store and verify their changes.

I am going to close this one and if you have any questions/concerns please raise them in one of the 2 PR's linked above.
