### ISSUE TITLE
mysteriouse stencil pull error

### ISSUE THREAD

**Issue by patomation** [bigcommerce/stencil-cli#567]
### Expected behavior
Inside of current theme folder shouldn't doing a ```stencil pull``` pull the client changes from the current theme? 

### Actual behavior
I get this error
```
not ok -- Error: Response Error: 404 Not Found see details below:
unknown error
If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.
```

### Steps to reproduce behavior
1. downloaded the zip file from the client
2. unzip it
3. change into downloaded theme directory
4. run ```sencil init``` put in store url and stencil token
5. run ```stencil pull``
6. get the error

Granted I am able to stencil push from this directory why wouldn't I be able to pull also?
Maybe I'm using the tool wrong. But intuitively it seems like it should work like this. 
Am I doing it wrong?

My Node version is 10.19.0

**Comment by bookernath** [comment]
@LordZardeck do you have any guidance here?

**Comment by carsonreinke** [comment]
@patomation I would think the theme with that name does not exist, because usually when the theme is uploaded and it is a duplicate name, you will see things like `(1)` appended.  Maybe check that the `config.json` theme name matches the name of the theme you on the storefront you are trying to pull from.

**Comment by patomation** [comment]
Thanks guys that seemed to work. It would be nice if the error message was more descriptive though.

**Comment by bookernath** [comment]
It seems like this is resolved so I'll be closing this.

By the way, `3.0` just released with a completely refactored `stencil pull` which is much faster. Give it a try!
