### ISSUE TITLE
Still seeing an error with --tunnel option

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#579]
Just commented that this issue still persists. Then realized @junedkazi said to open a new issue if it persists.

https://github.com/bigcommerce/stencil-cli/issues/538#issuecomment-588012625

**Comment by junedkazi** [comment]
@flyingL123 i don’t believe it is an issue with cli. See https://github.com/localtunnel/localtunnel/issues you will find tons of similar issues. I would say give it a couple of hrs and try again.

**Comment by flyingL123** [comment]
@junedkazi would you all consider using something besides localtunnel? Looks like it's not actively updated very often: https://github.com/localtunnel/localtunnel/issues/343#issuecomment-588241720

**Comment by flyingL123** [comment]
@junedkazi would you all consider using something besides localtunnel? Looks like it's not actively updated very often: https://github.com/localtunnel/localtunnel/issues/343#issuecomment-588241720

**Comment by junedkazi** [comment]
@flyingL123 unfortunately localtinnel is not something we support as a direct dependency. We are using browsersync to support the tunnel behavior. There are some old discussions on browsersync to add support https://github.com/BrowserSync/browser-sync/issues/192 but I don't see much progress there.

**Comment by junedkazi** [comment]
I am going to close this one since there is nothing much we can do here. We rely on browser sync and we should make an issue on that project to switch localtunnel to ngrok or something else.
