### ISSUE TITLE
npm install fails with a node-gyp/node-sass errors

### ISSUE THREAD

**Issue by jkelly-cas** [bigcommerce/stencil-cli#581]
This error is happening on the recommended node versions 10.16 from the docs, and 10.18.

If anyone else is having this issue, reverting back to node v8, and simply re-issuing `npm install`, will install everything correctly, but stencil requires node v10 now, so switch back over after it installs.

sass error
```
../src/sass_types/list.cpp: In static member function ‘static Sass_Value* SassTypes::List::construct(std::vector<v8::Local<v8::Value> >, Sass_Value**)’:
**../src/sass_types/list.cpp:28:73: error: too few arguments to function ‘Sass_Value* sass_make_list(size_t, Sass_Separator, bool)’**
   28 |     return *out = sass_make_list(length, comma ? SASS_COMMA : SASS_SPACE);
      |                                                                         ^
In file included from ../src/sass_types/value.h:5,
                 from ../src/sass_types/sass_value_wrapper.h:7,
                 from ../src/sass_types/list.h:5,
                 from ../src/sass_types/list.cpp:2:
```

gyp error
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/$user/work/projects/$themeFolder/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/home/$user/.nvm/versions/node/v10.16.3/bin/node" "/home/$user/work/projects/$themeFolder/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/$user/work/projects/$themeFolder/node_modules/@bigcommerce/stencil-styles/node_modules/@bigcommerce/node-sass
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed
```
npm error
```
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#4ea0b8d5f7c418d5bf20b07e395b2609e020bb8b postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#4ea0b8d5f7c418d5bf20b07e395b2609e020bb8b postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/$user/.npm/_logs/2020-03-05T19_17_36_259Z-debug.log
```
`stencil --version: 1.23.1`
`node --version: v10.16.3`
`npm --version: 6.13.4`

linking #417

**Comment by carsonreinke** [comment]
@jkelly-cas the problem is this [Sass fork](https://github.com/bigcommerce-labs/node-sass)

**Comment by ttran835** [comment]
I have been stuck on this issue for hours and hours. I thought it was my dependencies. Is this an issue in this package? 

This is my other post on BigCommerce for this issue. Btw, that solution is no help.

![BigCommerce](https://user-images.githubusercontent.com/39759466/76031788-43719a00-5eed-11ea-893d-4b5aea818042.png)
![BigCommerce2](https://user-images.githubusercontent.com/39759466/76031789-440a3080-5eed-11ea-99cd-cd66cf397fb1.png)

**Comment by carsonreinke** [comment]
@ttran835 the root of the problem is that Sass is a native dependency, meaning it literally compiles with a local library.  Depending on your system, there may be a missing or incorrect version of that native dependency.  Usually the problem turns out to be simply the wrong location or the wrong version.

If you provide the OS version, Node version and the actual error, I might able to tell you what is wrong.

Ultimately, it is a common problem and really should be an issue under https://github.com/bigcommerce-labs/node-sass to have it correctly fixed.

**Comment by ttran835** [comment]
@carsonreinke 

OS: MacOs Catalina 10.15.3
Node: v10.16.3
Node-gyp: v6.1.0
node-sass: 4.13.1	(Wrapper)	[JavaScript]
libsass: 3.5.4	(Sass Compiler)	[C/C++]

<img width="1261" alt="stencil-error" src="https://user-images.githubusercontent.com/39759466/76100211-24244c80-5f81-11ea-8a4c-e5a5e5b19046.png">

That's the error that I get at the last second. 

Please let me know if you are able to help me resolve this issue.

**Comment by carsonreinke** [comment]
@ttran835 what version of `stencil-cli` are you trying to install?

From what I am seeing, `@bigcommerce/node-sass` v3.5.0 used by `@bigcommerce/stencil-styles` used by `@bigcommerce/stencil-cli` has `libsass` v3.3.2 specifically included along with it.

Switching libsass with Homebrew to that version has proved nearly impossible.

**Comment by ttran835** [comment]
@carsonreinke 

I recently solved the issue by doing a complete reinstallation of nodejs on my OS. Also, the issue was within the theme that was copied down from BigCommerce. 
I tested out with BigCommerce default theme and it worked just fine.

Thank you for your help!

**Comment by junedkazi** [comment]
Please try the latest 3.x version. If you are still running into issues fee free to re-open or file a new issue.
