### ISSUE TITLE
Add to cart not working on localhost

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#585]
Please help. Originally reported here:

https://github.com/bigcommerce/cornerstone/issues/1653

**Comment by junedkazi** [comment]
@flyingL123 it is due to SameSite https://web.dev/samesite-cookies-explained/ cookies which was introduced in chrome. We are working on a fix but in the interim I would recommend using chrome 76 or less or use any other browser other than chrome.

**Comment by flyingL123** [comment]
Thanks so much for the quick response!

**Comment by bookernath** [comment]
You can also disable SameSite cookie protections in chrome in `chrome://flags` for now.

**Comment by junedkazi** [comment]
@flyingL123 can you please verify if this issue is fixed cli 2.0

**Comment by cmaycumber** [comment]
@junedkazi @flyingL123  I just ran into this issue today and upgrading to v2.0 of the cli fixed it.

**Comment by junedkazi** [comment]
Thank you @cmaycumber for verifying the fix.
