### ISSUE TITLE
Stencil CLI self signed certificate error

### ISSUE THREAD

**Issue by nhofer56** [bigcommerce/stencil-cli#587]
### Expected behavior
Install Stencil CLI and start developing BigCommerce theme(s)

### Actual behavior
I am trying to get Stencil CLI running on my workstation.  Installation was successful but I haven't been able to do much beyond that.  I can run 'stencil init' and configure all the needed parameters.  However, when I try 'stencil start -o', it starts nicely, but throws a 500 error.

I reached out to multiple people, but they just drew a blank.

It was when I tried running 'stencil pull' that I finally got a push in the right direction.  'stencil pull' threw a self signed certificate error.  I did a bunch of research and found it was our corporate network security that was causing this error.  I believe the above-mentioned 500 error stems from the same issue, the 'self signed certificate'

What is the best way to resolve this?

### Steps to reproduce behavior
Not sure how to reproduce this on other computers because this is on a company network with security software

**Comment by junedkazi** [comment]
@nhofer56 can you share additional information like what version of cli you are on and also your node version. Also can you check you `.stencil` file and tell me if the store url protocol i.e. http or https.

**Comment by nhofer56** [comment]
I am using the latest version of Stencil CLI, 1.23.1.  I installed the latest version probably a week ago.  Node version is 10.16, the current recommended version in the BigCommerce installation docs.  URL protocol calls for https.
Btw, I believe this issue is not related to installation.  I can run 'stencil start', but when I open a browser window to do a live preview, Stencil CLI asks Bigcommerce for information, and that is where certificate and 500 errors start.

**Comment by junedkazi** [comment]
I have a few follow up questions;

- Does your store works when you go to its actual url like https://example.com ? 
- Also for the 500 do you see any errors on your terminal or your browser console ?
- Can you please verify the issue exists with the latest cornerstone to rule out any theme modifications.

**Comment by nhofer56** [comment]
My store works - it is online and live.  https://stripcurtainswholesale.com

The 500 error shows up both in the terminal and browser window.  In the browser window I get this:
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}.
See the attached screenshots of the terminal window error when running 'stencil start -o' and 'stencil pull'
![stencil-pull-err](https://user-images.githubusercontent.com/52466870/77479552-057ddc80-6dee-11ea-81c8-584c32e9d411.jpg)
![stencil-start-err](https://user-images.githubusercontent.com/52466870/77479557-06167300-6dee-11ea-86f0-ca0cc845ba92.jpg)

I am using the latest Cornerstone theme on GitHub.  I have tried with a customized version of Cornerstone, but that didn't work so I downloaded the base Cornerstone and tried with that.  Same error.

**Comment by junedkazi** [comment]
@nhofer56 is it possible to turn off your network security/vpn for a few mins to confirm if that fixes the issue or may be use another machine which is not on the network. Did it ever work on the network ?

**Comment by nhofer56** [comment]
I can't turn off the network security, but I have successfully bypassed it using a mobile hotspot and connecting directly to the Internet through it.  When I do this, I can run 'stencil start' or 'stencil pull' and it works just like it was designed to.
What I don't understand is why this is an issue in the first place.  I can access my store, both front- and back-end, from the computer on which I am trying to run 'stencil start' and 'stencil pull'.  So why does it throw an error when accessing this information through the command line, but not when pulling it up through the store backend?

**Comment by junedkazi** [comment]
@nhofer56 sorry but there is nothing much we can do to help. You should work with your IT team to figure out what is the best possible way fix this issue.

**Comment by nhofer56** [comment]
I was afraid this was what you were going to say.  But why is it an issue when I pull up the same data through the browser?

**Comment by junedkazi** [comment]
This is just a thought and I am not security expert. We believe your VPN is doing deep packet inspection and the cert used for MITM (Man-in-the-middle attack) things is not getting accepted.
