### ISSUE TITLE
"stencil start" does not work in stencil-cli 2.0

### ISSUE THREAD

**Issue by jbruni** [bigcommerce/stencil-cli#588]
### Expected behavior
`stencil start` should serve the store theme on `http://localhost:3000`

### Actual behavior
Chrome browser error:

> This page isn’t working
> localhost didn’t send any data.
> ERR_EMPTY_RESPONSE

### Steps to reproduce behavior

Just install `stencil-cli` 2.0 globally, and run `stencil start` from root of Cornerstone theme properly configured with `.stencil`

**Comment by junedkazi** [comment]
@jbruni in cli 2.0 I merged a change in which browserSync will pick up the protocol on the store url stored in your `.stencil` file. So if it `https` try `http://localhost:3000`. It should display in the url with the right protocol when cli starts.

**Comment by jbruni** [comment]
@junedkazi - Indeed. Version 2.0 is serving the store assets using the same protocol of the store URL in `.stencil`

I don't know if this is a good behavior. In prior version, we could set the store URL in `.stencil` using the HTTPS protocol of the remote store, and use HTTP to develop locally. Now, to keep this behavior, we need to manually toggle the protocol in `.stencil` - this is not good.

Why not serve both `http` and `https`? This would be the best for stencil-cli, in my opinion.

**Comment by PeteyRev** [comment]
@junedkazi  is the cli manually generating a ssl on stencil start? It is causing a privacy error in chrome:

> its security certificate does not specify Subject Alternative Names. This may be caused by a misconfiguration or an attacker intercepting your connection.

and I cant seem to add my own ssl as it keeps defaulting to this one

**Comment by junedkazi** [comment]
This should be fixed in `2.1.1`
