### ISSUE TITLE
Installing on Mac OS Catalina

### ISSUE THREAD

**Issue by rohanleach4** [bigcommerce/stencil-cli#589]
Hello
I am trying to install Stencil locally onto Mac OS Catalina.

Node: v.10.16.3
Xcode: latest version

I am experiencing a a couple of issues that are stopping me from installing Stencil.
Firstly, it is painfully slow while ‘checking installable status’.
Secondly, after using **npm install -g @bigcommerce/stencil-cli** the installation stops when it tries to install git://github.com/bigcommerce-labs/node-sass.git
With this error:

798 verbose node v10.16.3
799 verbose npm  v6.9.0
800 error Error while executing:
800 error /usr/local/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
800 error
800 error undefined
800 error exited with error code: 128
801 verbose exit [ 1, true ]

Is there a solution or work around to this?
Thanks

**Comment by carsonreinke** [comment]
See #581, it might be the same issue.  I would try installing `bigcommerce-labs/node-sass` directly and see if any specifics.

**Comment by rohanleach4** [comment]
Thanks
bigcommerce-labs/node-sass (https://github.com/bigcommerce-labs/node-sass)
can be installed independently with **npm install node-sass** and this installs fine.
No errors.

**Comment by lord2800** [comment]
Can you try running that command manually?
```bash
/usr/local/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
```

**Comment by rohanleach4** [comment]
Sure.

/usr/local/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
results in this:
% /usr/local/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
fatal: unable to connect to github.com:
github.com[0: 81.99.162.48]: errno=Operation timed out

**Comment by lord2800** [comment]
Can you run `ssh -T git@github.com`?

**Comment by rohanleach4** [comment]
Now it gets interesting:

ssh -T git@github.com
ssh: connect to host github.com port 22: No route to host
I tried this again after switching off my firewall.
Same issue

**Comment by lord2800** [comment]
OK, so the problem seems to be that you can't talk to github. That's progress, at least! I assume you're using the same computer to post to this issue as you're running the commands from, so it has to be something about dns resolution in your terminal. What happens if you run `dig github.com` as well as `dig @8.8.8.8 github.com`?

**Comment by rohanleach4** [comment]
Hey - thanks for you time on this :)

dig github.com

; <<>> DiG 9.10.6 <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2049
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github.com.			IN	A

;; ANSWER SECTION:
github.com.		0	IN	A	81.99.162.48

;; Query time: 13 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Mon Mar 30 21:18:54 BST 2020
;; MSG SIZE  rcvd: 55

------

dig @8.8.8.8 github.com

; <<>> DiG 9.10.6 <<>> @8.8.8.8 github.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48438
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github.com.			IN	A

;; ANSWER SECTION:
github.com.		59	IN	A	140.82.118.4

;; Query time: 33 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Mar 30 21:19:22 BST 2020
;; MSG SIZE  rcvd: 55

**Comment by lord2800** [comment]
OK, it looks like your local resolver is returning an invalid ip address. Can you try switching your dns ip address to 8.8.8.8 (google's dns server), and then trying to run the install again?

**Comment by rohanleach4** [comment]
This works! Thank you.
