### ISSUE TITLE
unable to use stencil pull

### ISSUE THREAD

**Issue by Edwin-HS** [bigcommerce/stencil-cli#597]
not ok -- ThemeUploadError: [object Object] see details below:
unknown error
If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.

I get this issue when i installed stencil and init stencil on my BC.
I want to pull changed which i made at BC to my local machine. It gives me this message.

This occured since today.

**Comment by bookernath** [comment]
We've released 3.0 in which `stencil pull` is completely refactored. Is this issue resolved for you on 3.0?
