### ISSUE TITLE
Unable to sign in during local development

### ISSUE THREAD

**Issue by bdizzleog** [bigcommerce/stencil-cli#602]
### Expected behavior
Able to log in

### Actual behavior
I try to log in and it does nothing.

### Steps to reproduce behavior
Watch video, I have tried reinstalling stencil and npm packages everything. Does the same thing.
https://gyazo.com/398280b355dcf1abcbe48b21f0e3f33e

**Comment by brandonjp** [comment]
Ughh... I'm so sorry. This same exact thing happens to me quite frequently as well.  Sometimes I can log in, sometimes it's just a login loop.  I have not been able to track the exact reason why, but usually if I restart my computer, then create a fresh clone of my theme (customized Cornerstone) and npm install, it *sometimes* works.  

I've had so many problems with little things like this that I wrote a script to handle the re-fresh steps... clone theme, copy `.stencil` file, switch to dev branch, run `npm install`, commit `package-lock.json` changes, then finally 15 minutes later I'm able to run `stencil start` and start working.  I end up running this about 3 times a day & it at least helps with some stuff.  If you get to that point and want help on scripting your own, lmk

**Comment by bdizzleog** [comment]
Hmm I'm not sure, I couldn't seem to find a fix with that. It is a custom theme I purchased from ThemeForest. Nothing seems to fix the issue.

**Comment by bdizzleog** [comment]
> Ughh... I'm so sorry. This same exact thing happens to me quite frequently as well. Sometimes I can log in, sometimes it's just a login loop. I have not been able to track the exact reason why, but usually if I restart my computer, then create a fresh clone of my theme (customized Cornerstone) and npm install, it _sometimes_ works.
> 
> I've had so many problems with little things like this that I wrote a script to handle the re-fresh steps... clone theme, copy `.stencil` file, switch to dev branch, run `npm install`, commit `package-lock.json` changes, then finally 15 minutes later I'm able to run `stencil start` and start working. I end up running this about 3 times a day & it at least helps with some stuff. If you get to that point and want help on scripting your own, lmk

Thanks for your reply. I actually did try this and unfortunately it did not fix.

**My Solution was:**

Instead of typing: stencil start
I did: stencil start -o

And it automagically opened the browser and on the top-right it showed BrowserSync: Connected. Worked!

**Comment by junedkazi** [comment]
I believe this should be fixed with https://github.com/bigcommerce/stencil-cli/pull/652. Can you pull the latest 3.x and try again.
