### ISSUE TITLE
ESLint is no longer referenced during build

### ISSUE THREAD

**Issue by Ash-Matter** [bigcommerce/stencil-cli#603]
### Expected behavior
When running `stencil push` or `stencil bundle`, the project should be linted using ESLint and referencing `.eslintrc`.

### Actual behavior
On versions on and after 1.23, the call has been removed: https://github.com/bigcommerce/stencil-cli/commit/5a2fd8557fc73651bdcc39f4c48ea59dad5859ca#diff-235d6dde0d5441e67471ec65e5cdaf63L45

### Steps to reproduce behavior
Using a stencil-cli version on or after v1.23, run `stencil bundle` or `stencil push`. `Running ESLint...` never occurs.

**Comment by junedkazi** [comment]
@Ash-Matter One of the big reasons for removing it was it makes it very hard to be backward compatible and hard to upgrade eslint. TBH stencil cli should not be doing the linting for the themes and It should be part of your development flow.

**Comment by carsonreinke** [comment]
@junedkazi ...also, the ESLint was different from Cornerstone: https://github.com/bigcommerce/cornerstone/blob/master/grunt/eslint.js

Maybe it the future BC would be open to adding hooks for automatically running linters on build?

**Comment by junedkazi** [comment]
@carsonreinke yes that is exactly the reason for the removal. It will be hard to keep the version in sync across all themes. We should definitely look into adding some kind of hooks or a plugin flow where you could add it to the bundle process. But for now I am going to close this as won't fix.
