### ISSUE TITLE
Getting Error: You are using an outdated version of stencil-cli, please run $ npm install -g @bigcommerce/stencil-cli on stencil start

### ISSUE THREAD

**Issue by cookseyth** [bigcommerce/stencil-cli#625]
I originally submitted this issue here: https://support.bigcommerce.com/s/question/0D54O00006YahaWSAR/getting-error-you-are-using-an-outdated-version-of-stencilcli-please-run-npm-install-g-bigcommercestencilcli-on-stencil-start

I looked through https://support.bigcommerce.com/s/question/0D51B00005Lx5Qo/getting-error-you-are-using-an-outdated-version-of-stencilcli and that did not help me. The store URL is what it's supposed to be and I reset the .stencil file as well and did not work either. I've reinstalled node and npm and that did not change anything.

I had been using my current theme file for a while and it just stopped working. I tested a fresh Cornerstone file and it worked fine.

**Comment by junedkazi** [comment]
@cookseyth we will need additional information as to what is your node version which OS are you on and what is the current cli version you are on. If there are any errors on the console when you do `stencil start`. There is not enough information for us to help you with the issue.

**Comment by cookseyth** [comment]
@junedkazi I fixed it, after submitting the issue on here I thought to update my theme to newest cornerstone files and that fixed it.
