### ISSUE TITLE
Live theme not retrieving custom files in assets directory

### ISSUE THREAD

**Issue by asiejnapsc** [bigcommerce/stencil-cli#626]
### Expected behavior
Any new script or style files should be able to be pulled onto the live theme.

Here is my local environment showing that the references to the file paths are correct and my styles/scripts are being applied properly.

![Local Host](https://i.imgur.com/f6lbcGw.png)

### Actual behavior

After pushing my theme and testing on the live store, I am getting errors in the console about files not being found. 

Here is the live URL of the site.
![Live](https://i.imgur.com/5ooXJbW.png)

Here is my console.
![Console](https://i.imgur.com/8ys7H70.png)

### Steps to reproduce behavior

1. Create a new directory and new files inside (script or styles) within the /assets/ directory
![Asset Directory](https://i.imgur.com/W9v3bfH.png)

2. Make reference to that directory in a template (home.html for example)
 `<link rel="stylesheet" href="assets/homepage/css/bootstrap.css">` 

3. View template in localhost 

4. Run `stencil push`

5. View template on live site

**Comment by junedkazi** [comment]
@asiejnapsc can you share the code you are using to get the files ? I am hoping you are using https://developer.bigcommerce.com/stencil-docs/storefront-customization/theme-assets as a guideline to load the assets.

**Comment by asiejnapsc** [comment]
@junedkazi 

Whoops, looks like my markup hid my reference to loading the assets. For recreating the error, point 2. 
 `<link rel="stylesheet" href="assets/homepage/css/bootstrap.css">` as an example

I'll edit that above as well.

**Comment by junedkazi** [comment]
Can you try this 
```
        {{{stylesheet '/assets/homepage/css/bootstrap.css'}}}
```
See https://developer.bigcommerce.com/stencil-docs/storefront-customization/custom-sass-functions#compiling-custom-sass-files as to how to load css files

**Comment by asiejnapsc** [comment]
@junedkazi 

I see, I must use Handlebars formatting to reference those. That seems to work for both my local and live theme. 

One more question for you, what would the Handlebars syntax be for 'script' files? I have several custom JS files that are also within the assets directory. Example: `<script src="assets/homepage/js/jquery.fullPage.min.js"></script>`

Thank you for your help with this.

**Comment by junedkazi** [comment]
Something like this 
```
<script src="{{cdn 'assets/homepage/js/jquery.fullPage.min.js'}}"></script>
```

**Comment by asiejnapsc** [comment]
That worked perfectly. Thank you so much for your time and help with this!
