### ISSUE TITLE
Stencil localhost:3000 showing Unauthorized Sorry, you are not authorized to access this page.

### ISSUE THREAD

**Issue by CelesteComet** [bigcommerce/stencil-cli#629]
I was developing as usual yesterday with my API credentials and today it suddenly stopped working. I created a new set of API credentials and it still doesn't work. is there something wrong on bigcommerce's end?

**Comment by junedkazi** [comment]
@CelesteComet yes we are aware of the issue and investigating

**Comment by CelesteComet** [comment]
Thanks you guys are awesome

**Comment by Mackkkk** [comment]
similar problems

**Comment by HATECORO** [comment]
me too

**Comment by arashi22** [comment]
same problem (unauthorized)

**Comment by jamiekpac** [comment]
Just wanted to check in and see if there's any update on this ticket (ETA / in progress)?

**Comment by junedkazi** [comment]
We are deploying a fix at this moment. It will take another 15-20 mins to be completely rolled out.

**Comment by jamiekpac** [comment]
> We are deploying a fix at this moment. It will take another 15-20 mins to be completely rolled out.

Amazing, thanks for the update!
Also - we appreciate the quick response time on the issue :)

**Comment by HATECORO** [comment]
> me too
> stencil version: `2.1.1`
> popup shows:
> **Unauthorized Sorry, you are not authorized to access this page.**

大哥，好了给我说一声喃

**Comment by junedkazi** [comment]
Just want to give a quick update. The deploys are still going out. Please give us some more time we will get this sorted quickly. Apologies for all the inconvenience.

**Comment by LeoChowChina** [comment]
> Just want to give a quick update. The deploys are still going out. Please give us some more time we will get this sorted quickly. Apologies for all the inconvenience.

Thanks for the update.

**Comment by junedkazi** [comment]
The issue should be now resolved.
