### ISSUE TITLE
Updating stencil-cli to node version 12+

### ISSUE THREAD

**Issue by reijovosu** [bigcommerce/stencil-cli#633]
Since node 10 EOL is beginning to come very close. I think it is time to upgrade stencil-cli
Also forcing people to use nvm is outputting for a lot of developers

### Expected behavior
stencil-cli working on node 12

### Actual behavior
stencil-cli not working on node 12

### Steps to reproduce behavior
try to install.

**Comment by MaxGenash** [comment]
We are already working on updating to Node 12 (firstly need to update a lot of outdated dependencies), so it's coming soon :)

**Comment by reijovosu** [comment]
Sounds good. Can't wait:D
