### ISSUE TITLE
checkout.html changes work in development but have no effect in production

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-cli#668]
### Expected behavior
If I make a change in `templates/pages/checkout.html` file, I am able to see it as expected when running my theme locally with stencil.

### Actual behavior
After deploying the theme to the live store, I see the single-page optimized checkout as expected, but the change I made is not present.

### Steps to reproduce behavior
In the `checkout.html` file, I add the highlighted line:
![image](https://user-images.githubusercontent.com/2486712/99769802-e5b1cc00-2ad4-11eb-9242-a787b8f15497.png)

View the checkout locally and that new line is visible in the source:

![image](https://user-images.githubusercontent.com/2486712/99769911-1134b680-2ad5-11eb-8776-abe62e6b3e5f.png)

Deploy the checkout to the live website, and the new line is not there:

![image](https://user-images.githubusercontent.com/2486712/99770026-39bcb080-2ad5-11eb-9c4e-17af0856311b.png)

Is there something that would cause these changes to not appear on the live site? My store is set to use "Optimized One-Page Checkout". This method of customizing has been working for me for a while. Did something change that would cause this not to work or is there a bug of some kind?

**Comment by flyingL123** [comment]
Apologies, I meant to post this in the cornerstone repo. I just did:

https://github.com/bigcommerce/cornerstone/issues/1909

**Comment by junedkazi** [comment]
Closing this in favor of https://github.com/bigcommerce/cornerstone/issues/1909
