### ISSUE TITLE
Error: You must have a  config.json file in your top level theme directory

### ISSUE THREAD

**Issue by mycabau13** [bigcommerce/stencil-cli#678]
### Expected behavior
I'm trying to start the stencil cli, but when i run the command "stencil start" on my terminal, I get the result of 
"not ok -- Error: You must have a  config.json file in your top-level theme directory."

### Steps to reproduce behavior
I have checked BigCommerce store to see if the config.json file is there with the theme that I have through the edit theme files. The file is there. I'm not sure why I am getting this error.

**Comment by gabrielxfive** [comment]
Hi @mycabau13 How did you fix this issue?

**Comment by FatmaOthman** [comment]
@gabrielxfive hi did you solve the problem?

**Comment by LewisHoneypot** [comment]
@mycabau13 @gabrielxfive @FatmaOthman 

It could be that you're not running "stencil start" from the correct location, try navigating to the theme directory using your terminal and running the command again.
