### ISSUE TITLE
Cannot install stencil-cli in WSL 2 w/Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by mtrivera** [bigcommerce/stencil-cli#684]
### Expected behavior

To install stencil-cli globally.

### Actual behavior

Error on install.
[npm-error-log.txt](https://github.com/bigcommerce/stencil-cli/files/6031263/npm-error-log.txt)

### Steps to reproduce behavior
Run `npm install -g @bigcommerce/stencil-cli` in WSL 2 w/Ubuntu 20.04 LTS

## System Information
Windows 10 build 19042.804
WSL 2 w/Ubuntu 20.04.1 LTS
node version 12.19.0

**Comment by pvaladez** [comment]
I am able to install stencil-cli with npm version 6.14.11, but I see the same errors with any of the npm version 7 releases.  I'm also running WSL 2 w/Ubuntu 20.04.1 LTS and node version 12.21.0

**Comment by mtrivera** [comment]
That's odd. Well, I'll be looking into using Docker. I have a short deadline and I can't spend too much time on this problem. Thanks for your input.

**Comment by thetechie92** [comment]
It also happens with PowerShell as well. I believe the issue using stencil-cli with node version 12.21.0.

**Comment by obrien-k** [comment]
> ### Expected behavior
> To install stencil-cli globally.
> 
> ### Actual behavior
> Error on install.
> [npm-error-log.txt](https://github.com/bigcommerce/stencil-cli/files/6031263/npm-error-log.txt)
> 
> ### Steps to reproduce behavior
> Run `npm install -g @bigcommerce/stencil-cli` in WSL 2 w/Ubuntu 20.04 LTS
> 
> ## System Information
> Windows 10 build 19042.804
> WSL 2 w/Ubuntu 20.04.1 LTS
> node version 12.19.0

Hey there,

I haven't used Stencil CLI on WSL 2 too often, but usually when working with WSL 2 and I run into issues running as `sudo` resolves it but this isn't typically advised for *-nix based systems. Are you able to temporarily resolve this by running the command as `sudo` ?
