### ISSUE TITLE
npm throws errors when i trying to install stencil cli on my windows

### ISSUE THREAD

**Issue by DeveloperCharles** [bigcommerce/stencil-cli#694]
### Expected behavior
use command npm install -g @bigcommerce/stencil-cli in bigcommerce docs successfully install stencil cli on my computer

### Actual behavior
some errors threw out by npm when it proceed to install node-sass by bigcommerce-labs
and it tells me that templates not found in some of my local folders

### Steps to reproduce behavior
follow bigcommerce docs on how to get stencil cli installed on my windows
succeeded almost every steps but failed at the last step npm install -g @bigcommerce/stencil-cli

**Comment by DeveloperCharles** [comment]
![image](https://user-images.githubusercontent.com/34536912/111874945-34636a00-89d2-11eb-8f76-298a146b2577.png)
this is the errors that npm threw out

**Comment by DeveloperCharles** [comment]
![image](https://user-images.githubusercontent.com/34536912/111875081-d8e5ac00-89d2-11eb-8b4a-f7065f30efa0.png)
and this is my current tools on my computer(windows)

**Comment by DeveloperCharles** [comment]
anyone if you had encountered this issue or fixed this issue by any ways, please help
i have stuck on installing stencil cli to my computer for days

**Comment by MaxGenash** [comment]
@DeveloperCharles the error you encounter says "...unable to connect to github.com...".
I suspect that you probably have some issues with DNS, VPN, or installed git.
Not with stencil-cli itself

**Comment by MaxGenash** [comment]
try this solution https://github.com/npm/npm/issues/6285#issuecomment-56640354

**Comment by DeveloperCharles** [comment]
> @DeveloperCharles the error you encounter says "...unable to connect to github.com...". I suspect that you probably have some issues with DNS, VPN, firewall, or installed git. Not with stencil-cli itself.

Thanks for your reply! And sincerely sorry for not checking this for a really long time...
The fact is, the company office does have a bad network condition, it really drive me crazzzzy..

Thanks again for you time and answer!
