### ISSUE TITLE
Error installing Stencil-CLI

### ISSUE THREAD

**Issue by creativewhs** [bigcommerce/stencil-cli#695]
### Expected behavior
Stencil CLI installation

### Actual behavior
git error

### Steps to reproduce behavior
Followed the steps here: https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/installing-stencil
On the final step of installing Stencil CLI via: npm install -g @bigcommerce/stencil-cli
I get this error. Followed the steps on another PC on my network and the installation was successful.

![Screenshot 2021-03-22 074111](https://user-images.githubusercontent.com/13133604/111984660-08cfa500-8ae2-11eb-9fa2-855aaa466df5.png)

PS C:\Windows\system32> npm install -g @bigcommerce/stencil-cli
>>
npm WARN deprecated @hapi/hapi@18.4.1: This version contains severe security issues and defects and should not be used! Please upgrade to the latest version of @hapi/hapi or consider a commercial license (https://github.com/hapijs/hapi/issues/4114)
npm WARN deprecated @hapi/boom@8.0.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by creativewhs** [comment]
I ended up

**Comment by dsutphin** [comment]
This happens for me when using npm 7.8.0 (latest). But not 6.14.11 (what `nvm install 12.3` includes).
