### ISSUE TITLE
Could not fetch a list of the store channels: Request failed with status code 403

### ISSUE THREAD

**Issue by sacr3dc0w** [bigcommerce/stencil-cli#697]
### Expected behavior

Run `stencil push` to deploy local changes.

### Actual behavior

Uploads and processes theme successfully, then fails.

`not ok -- Error: Could not fetch a list of the store channels: Request failed with status code 403`

### Steps to reproduce behavior

NPM: 6.14.11
Node: 12.21
NVM: 0.31.0

Fresh install of stencil-cli and run `stencil push`.

**Comment by junedkazi** [comment]
@sacr3dc0w can you share what version of stencil cli you are on. Also is this a new oauth token or an existing one ?

**Comment by MaxGenash** [comment]
@sacr3dc0w, unfortunately, I couldn’t reproduce the bug for my store.
Could you try creating a new token? Also, make sure you selected "Publish themes" permission.
The old one shouldn’t have expired, but just in case.

<img width="950" alt="Screenshot 2021-03-24 at 20 28 53" src="https://user-images.githubusercontent.com/12990348/112366423-75fd5900-8ce1-11eb-8e83-e08f945003a6.png">

**Comment by sacr3dc0w** [comment]
@MaxGenash Created a new token and pushed without a problem. You're a life saver - Thanks a bunch!
