### ISSUE TITLE
Request failed with status code 403 while pushing theme(stencil push)

### ISSUE THREAD

**Issue by kajalMkorat** [bigcommerce/stencil-cli#705]
Hello,

Can you please help me?

when I push the theme getting a "Request failed with status code 403" error.
p
![error](https://user-images.githubusercontent.com/5525031/113498448-95d71d00-952a-11eb-9f0c-268d15b3e1da.jpg)

Thank you

**Comment by junedkazi** [comment]
@kajalMkorat can you please try with a new token and see if you are still experiencing the same issue ?

**Comment by kajalMkorat** [comment]
Hello junedkazi,

Oh yes, we've tried with a new token still getting the same error.

Thank you

**Comment by kajalMkorat** [comment]
Hello,

Ok Now working fine.
We've just created a new stencil-CLI token. before we used v2/v3 API token.

Thank you
