### ISSUE TITLE
How do you find what channel_id to use with `stencil push --channel_id` for main BigCommerce channel?

### ISSUE THREAD

**Issue by harnerdesigns** [bigcommerce/stencil-cli#718]
I can't figure out what to put for the `--channel_id` flag on `stencil push`. I'm just trying to push the theme to the main BigCommerce Channel. 

I know you can find Channel Id from the Channel Manager for everything else, but I can't find the main one.

**Comment by bookernath** [comment]
It's always `1` for the default storefront. We should probably make it a default in code as well.

**Comment by harnerdesigns** [comment]
Ok Perfect. `stencil push -c 1` worked perfect!
