### ISSUE TITLE
GraphQL Front Matter Query Not Working with Stencil-Cli

### ISSUE THREAD

**Issue by pvaladez** [bigcommerce/stencil-cli#732]
### Expected behavior
We should see the data returned in the `gql` context key when running a theme locally with `stencil start`.

### Actual behavior
While I do see the data after uploading and applying the theme to a store, the the `gql` context key appears be `undefined` when running locally with `stencil start`

Local environment version info:
```bash
[11:33:08] cornerstone$node -v
v12.22.3
[11:33:13] cornerstone$npm -v
6.14.13
[11:33:19] cornerstone$stencil --version
3.3.0
```

The theme used was `cornerstone version 5.7.0`

I did this test running on WSL2 Ubuntu, but I've also tried running natively on Windows.

### Steps to reproduce behavior
Insert the following simple query at the bottom of the `product.html` front matter block:

```yml
gql: "query productById($productId: Int!) {
 site {
   product(entityId: $productId) {
    description
   }
  }
 }
 "
 ```
 
Also put this at the top of `product.html` to see the data returned in the gql context key:
 ```handlebars
 <h1>GQL data: {{gql.data.site.product.description }}</h1>
 ```

**Comment by sacr3dc0w** [comment]
I can confirm that it's not working on Mac OS (11.4) as well.

Local environment version info:
```
matt@Matts-iMac creativesafetysupply.com % node -v
v12.21.0
matt@Matts-iMac creativesafetysupply.com % npm -v
6.14.11
matt@Matts-iMac creativesafetysupply.com % stencil --version
3.3.0
```

**Comment by gabealeman** [comment]
Same issue here

**Comment by piran-e2x** [comment]
I see absolutely nothing on my local development (no value in settings, no web traffic)
But when I push the code to my Sandbox it appears to work.

**Comment by sjb9774** [comment]
I'm also seeing this issue -- appears there must be a bug, or this documentation needs to be updated to clarify if it's not expected to work locally: https://developer.bigcommerce.com/stencil-docs/reference-docs/front-matter-reference#graphql-attributes

**Comment by tarponjargon** [comment]
same here. does anyone know, is this by design or is it a bug?

**Comment by jp06** [comment]
> same here. does anyone know, is this by design or is it a bug?

It's a bug. Someone (which I think is like a BigCommerce support guy) has responded to my question [here](https://stackoverflow.com/questions/68811642/bigcommerce-stencil-graphql-query-using-front-matter-not-returning-anything#comment121620879_68811642).

**Comment by zvuki** [comment]
This is fixed. Please let us know if you face any issues.

**Comment by tomhelmer** [comment]
I have just tried the example from the documentation and nothing happens. Where is the fix implemented ? in the theme or in the stencil client ?
