### ISSUE TITLE
Stencil push upload fails at 12%

### ISSUE THREAD

**Issue by Judder** [bigcommerce/stencil-cli#776]

**Comment by jairo-bc** [comment]
I think this errors happens, when your zip file exceeds 50MB. 

Check here: https://developer.bigcommerce.com/stencil-docs/deploying-a-theme/checking-a-themes-size

**Comment by AnirudhSingal91** [comment]
if your image files are too large, you can upload them through webdav separately

**Comment by Judder** [comment]
Thanks everyone - yes turns out there is a limit on the size of Theme preview images of 5Mb which we were just over. Readjusting the image and resubmitting the theme fixes this so all good, many thanks

https://developer.bigcommerce.com/stencil-docs/deploying-a-theme/preparing-thumbnail-images

**Comment by Judder** [comment]
Some decent debugging information from Stencil / BigCommerce would be nice though please BC team :)

**Comment by jairo-bc** [comment]
@Judder We are going to update some error messages to give more context to the users

**Comment by Judder** [comment]
Definitely - the problem with SAAS platforms like BigCommerce is that it is basically a black box - we send it requests and it gives us answers - but there is no way of accessing the log files or error reports when something doesn't happen as expected, so we are basically relying on these return answers to tell us _where_ to start looking for any problems.

If we could get something like:

error message (TR-300) | specific error message (file size too large) | detailed error message (name of file)

That would make like _much much_ easier
