### ISSUE TITLE
Storefront API responses include unwanted header attributes causing `set-cookie` headers to get blocked by browser.

### ISSUE THREAD

**Issue by churdstheword** [bigcommerce/stencil-cli#792]
### Expected behavior
When using `stencil-start` to develop locally, requests made to the Storefront API should not include the "Secure" or "SameSite=none" attributes in the "Set-Cookie" response header.

### Actual behavior
When using `stencil-start` to develop locally, requests made to the Storefront API are including the "Secure" and/or "SameSite=none" attributes in the "Set-Cookie" response header. This causes the web browser to block the incoming "Set-Cookie" header. 

For us, this mainly has caused carts to mysteriously disappear and reappear during local development, which has made developing some features rather difficult for us.

### Steps to reproduce behavior
```bash
# Run stencil init, if needed
stencil init

# Start up stencil
stencil start -v ${THEME} -c ${CHANNELID}

# From another terminal, curl the endpoint, and inspect the headers
curl -i http://localhost:3000/api/storefront/cart
```

### Environment
![image](https://user-images.githubusercontent.com/26151018/139865230-cd9d0a70-8827-4d75-8333-61d705f03f38.png)

OS:
Docker, based on the “node:12” image, which is running in WSL2 on Windows

**Comment by zvuki** [comment]
@churdstheword could you post your stencil-cli version?

**Comment by churdstheword** [comment]
Certainly, its 3.6.3, as shown in the screenshot above.

**Comment by jairo-bc** [comment]
Hi @churdstheword!

Could you please help me reproduce this issue and email your store details (url and id) to my work email (jairo.panduro@bigcommerce.com)?

**Comment by churdstheword** [comment]
Sent

**Comment by churdstheword** [comment]
To be more clear, while we developing, using stencil, we exclusively are connecting to the sandbox store.

**Comment by churdstheword** [comment]
After some research, I have discovered that something was wrong with my development environment. While I was confidant I was using v3.6.3 of the stencil-cli, before, after deleting the "node_modules" directory and reinstalling all of the project dependencies from the ground up, I am no longer unable to reproduce the issue as described. I can confirm that v3.6.3 does correct the issue as described. 

I will close out this issue. Thank for your time!
