### ISSUE TITLE
stencil start libsass error

### ISSUE THREAD

**Issue by IlyaT21** [bigcommerce/stencil-cli#816]
### Expected behavior
Starting Stencil CLI after running stencil start command

### Actual behavior
Following error is thrown:
not ok -- Error: The `libsass` binding was not found in C:\Users\Ilija\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\@bigcommerce\node-sass\vendor\win32-x64-72\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

Ran npm rebuild node-sass and npm rebuild node-sass --force but the error is still present after running stencil start

### Steps to reproduce behavior
I followed the instructions in this video: https://www.youtube.com/watch?v=kSgklTQunZU&list=WL&index=7&ab_channel=BigCommerce

I saw on one thread that this error is thrown when a vendor folder is missing, but I checked and it's there

### Environment
Visual Studio Code, Bash Terminal

Stencil-cli version `stencil --version`: 3.7.1

Node version `node -v`: 12.13.0

NPM version `npm -v`: 6.14.6

OS: Windows 10

**Comment by dannyissocool** [comment]
I'm having this same issue. Running `npm rebuild node-sass` doesn't seem to change anything. 

**Environment**
VS Code, Bash Terminal
Stencil-cli version: 3.8.0
Node version: 12.13.0
NPM version: 6.12.0
OS: Windows 10

**Comment by altugyavuz7** [comment]
Can you try with Node version 12.0.0?

**Comment by IlyaT21** [comment]
> Can you try with Node version 12.0.0? This was the only Node version I was able to run when I got the same error.

Did it, still the same error, no matter what I do. Did you use NVM to change the node version for this project?

**Comment by IlyaT21** [comment]
> I'm having this same issue. Running `npm rebuild node-sass` doesn't seem to change anything.
> 
> **Environment** VS Code, Bash Terminal Stencil-cli version: 3.8.0 Node version: 12.13.0 NPM version: 6.12.0 OS: Windows 10

In my package.json file, the node-sass isn't even added as a dependency, I added it with npm i node-sass or yarn add node-sass, but running the command npm rebuild node-sass --force does seem to rebuild it, but the error is still the same.

**Comment by TheHandOfKing** [comment]
Bumping this as my salary depends on solving this error, please make a better cli in the future

**Comment by TheHandOfKing** [comment]
Actually I solved this for u, but I wont tell it to anyone just to keep people on their toes @IlyaT21

**Comment by IlyaT21** [comment]
The way to do it is to delete @Bigcommerce folder @ C:\Users\[Your Username]\AppData\Roaming\npm\node_modules and delete stencil files in C:\Users\[Your Username]\AppData\Roaming\npm and run command npm install -g @bigcommerce/stencil-cli to install it again with an adequate node version (in my case it was 12.0.0). Problem is caused because the Bigcommerce stencil was installed with a version of node that is not supported.
