### ISSUE TITLE
Stencil workflow fails due to API Host prompt in Github Action

### ISSUE THREAD

**Issue by steve-ross** [bigcommerce/stencil-cli#844]
### Expected behavior

Workflow [in cornerstone example](https://github.com/bigcommerce/cornerstone/blob/master/.github/workflow-examples/poll_for_changed_configuration.yml) succeeds 

### Actual behavior

Due to there not being a bypass on the API Host prompt for `stencil init` the config file is not generated and the check will fail. (see screenshot)

![image](https://user-images.githubusercontent.com/297351/150026417-18874bb2-7b6c-4483-a558-355bbe85a974.png)

### Steps to reproduce behavior

Clone repo and use the workflow on a sandbox store. 

### Environment

Here is how I got it working (quite a bit of a hack/unreliable solution with the printing of newline)
![image](https://user-images.githubusercontent.com/297351/150026593-3c52fc93-6f4c-437e-9b8c-4645aef44f1c.png)

**Comment by jairo-bc** [comment]
Hi @steve-ross! Did you update stencil cli token after updating to the latest version? 

There was a breaking change at 3.7.0 version https://github.com/bigcommerce/stencil-cli/blob/master/CHANGELOG.md

**Comment by steve-ross** [comment]
Ah, thanks @jairo-bc  that's likely the culprit. I'm having another odd issue with a deployment workflow where the sass compilation breaks and it's extremely difficult to debug since it is not working locally and there are no errors in the logs. Should I open a ticket with support for that?

**Comment by jairo-bc** [comment]
@steve-ross Could you please share your store details to my corporate email? (jairo.panduro@bigcomerce.com)
I will take a look

**Comment by steve-ross** [comment]
@jairo-bc still failing due to the prompt on my action
![image](https://user-images.githubusercontent.com/297351/150172995-0af1e680-1830-4356-926f-4a22a16ce54f.png)

**Comment by jairo-bc** [comment]
@steve-ross Try to add `-h https://api.bigcommerce.com`

**Comment by steve-ross** [comment]
@jairo-bc thanks, that worked! Also, emailed you regarding the deployment issue. Going to open a support ticket to track it.
