### ISSUE TITLE
not ok -- VariationActivationError: channelIds.map is not a function

### ISSUE THREAD

**Issue by joelzerner** [bigcommerce/stencil-cli#848]
### Expected behavior

The theme will be pushed up and applied to my Big Commerce instance

### Actual behavior

I see this error:
not ok -- VariationActivationError: channelIds.map is not a function

### Steps to reproduce behavior

stencil push
? Would you like to apply your theme to your store? Yes
? Which variation would you like to apply? Main
not ok -- VariationActivationError: channelIds.map is not a function

### Environment

Stencil-cli version `stencil --version`:
3.8.5

Node version `node -v`:
v12.22.9

NPM version `npm -v`:
6.14.15

OS:
MacOS 11.6

**Comment by AndrewBarber** [comment]
Hey @joelzerner,

It looks like stencil-push was recently changed to support multiple channel push, however, there seems to be a bug when there is only one active 'site'.

One way to get around it at the moment is to specify the channel, the default is always `1` 

So your command would be `stencil push ... -c 1`

**Comment by matthewvolk** [comment]
Hi @joelzerner + @AndrewBarber! 

We just released `@bigcommerce/stencil-cli@3.9.0` which should resolve this issue. When you have a chance, could you update your local Stencil CLI version and see if you can push without explicitly specifying the Channel ID (`-c 1`)?

Thank you @AndrewBarber for the workaround! 

cc: @bc-hnbarr

**Comment by joelzerner** [comment]
Thanks!

I've updated to v3.9.0 and that has resolved the issue.
