### ISSUE TITLE
When I typed stencil pull, I received this error message.not ok -- Error: Could not fetch active theme details for channel undefined: Request failed with status code 400

### ISSUE THREAD

**Issue by JinMengmeng1998** [bigcommerce/stencil-cli#856]
![image](https://user-images.githubusercontent.com/71995351/150725362-c0155a25-8c74-4652-80f6-ad5bb93d456c.png)
Can someone tell me what's going on here?

Stencil-cli version `stencil --3.9.0`:

Node version `node -12`:

NPM version `npm -6.9`:

OS: windows 10

**Comment by jairo-bc** [comment]
@JinMengmeng1998 could you please check with latest version (3.9.1)?

**Comment by JinMengmeng1998** [comment]
> @JinMengmeng1998你能检查一下最新版本（3.9.1）吗？

Version 3.9.1 solved my problem, thank you very much。
