### ISSUE TITLE
Stencil push problem - 

### ISSUE THREAD

**Issue by codal-nilayp** [bigcommerce/stencil-cli#894]
Error : 
not ok -- Error: ENOENT: no such file or directory, open '/home/circleci/repo/config.json'

I am trying to deploy with circle ci and facing the error during "stencil push"
https://nimb.ws/n48La5

**Comment by jairo-bc** [comment]
Hi @codal-nilayp, you should run `stencil` commands inside theme folder. The error says, that it cannot find `config.json` in the path `/home/circleci/repo`
