### ISSUE TITLE
Cannot find module webpack

### ISSUE THREAD

**Issue by liamxtensive** [bigcommerce/stencil-cli#902]
### Expected behavior

Trying to run site locally so stencil start would be successful. This is to run Cornerstone 4.4.0

### Actual behavior

Error: Cannot find module 'webpack'
Require stack:
- /path-to-directory/stencil.conf.js
- /.nvm/versions/node/v12.22.7/lib/node_modules/@bigcommerce/stencil-cli/lib/BuildConfigManager.js
- /.nvm/versions/node/v12.22.7/lib/node_modules/@bigcommerce/stencil-cli/lib/stencil-start/js
- /.nvm/versions/node/v12.22.7/lib/node_modules/@bigcommerce/stencil-cli/bin/stencil-start.js

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helps.js:74:18)
at Object.<anonymous> (path-to-directory/stencil.conf.js:1:15)

Also this shows up in command line when I try to do npm install:

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
npm ERR! Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
npm ERR! 
npm ERR! exited with error code: 128

### Environment

Stencil-cli version `stencil --version`: 3.7.0

Node version `node -v`: 12.22.7

NPM version `npm -v`: 6.14.15

OS: Mac Monterey 12.0.1

**Comment by jairo-bc** [comment]
@liamxtensive Github is no longer supporting git protocol, we changed the protocol in the latest versions. My recommendation is to update `stencil cli` to the `latest` version

**Comment by liamxtensive** [comment]
@jairo-bc Updated to 3.12 and issue persists.

**Comment by jairo-bc** [comment]
From your log messages, I can say that there were 2 problems:
1. npm ERR! The unauthenticated git protocol on port 9418 is no longer supported.
It happens because of the old stencil cli version is being used. 
here it is https://github.com/bigcommerce/cornerstone/blob/4.4.0/package.json#L32

2. With the second one, I won't be able to help you and recommend to ask theme owners at https://github.com/bigcommerce/cornerstone, how to update correctly theme version (you have the version that is 2 year old)

**Comment by liamxtensive** [comment]
I got it by updating the CLI number in package.json. I would have though having the recent CLI installed would have forced it onto that.
