### ISSUE TITLE
not ok -- Error: Could not fetch a list of the store channels: Request failed with status code 403

### ISSUE THREAD

**Issue by captiva-megan** [bigcommerce/stencil-cli#905]
### Expected behavior
successful stencil start

### Actual behavior
not ok -- Error: Could not fetch a list of the store channels: Request failed with status code 403

OR

not ok -- Error: Could not fetch a list of the store channels: Request failed with status code 404

(I have gotten both codes now at different times. I get a 403 when pulling a clean copy of Cornerstone 6.3.0 from a client site; my coworker gets a 404 when doing the same. We have tested using API for two different stores, neither of which is using a proxy-based domain service.)

### Steps to reproduce behavior
Download a theme from a store.

Run stencil init with URL and token from a client site.

Run npm install.

Attempt to run stencil start.

### Environment

Stencil-cli version `stencil --version`:
3.12.0

Node version `node -v`:
12.1.0

NPM version `npm -v`:
6.9.0

OS:
macOS Monterey 12.2.1

**Comment by jairo-bc** [comment]
Hi @captiva-megan, do you have a fresh stencil cli token?

**Comment by jairo-bc** [comment]
@captiva-megan Thanks for the suggestion! We have added it here https://github.com/bigcommerce/stencil-cli/releases/tag/3.7.0, but I think we need to add it there as well, as people tend to look there for troubleshooting as well.

**Comment by daguitosama** [comment]
Yeah got it the same error and fixed the same way. Thanks God I find this so quickly 😂
