### ISSUE TITLE
not ok -- Error: Could not fetch a list of the store channels: Request failed with status code 401

### ISSUE THREAD

**Issue by TargetRhino** [bigcommerce/stencil-cli#911]
### Expected behavior

stencil init: 

What is the URL of your store's home page? https://store.com
What is your Stencil OAuth Access Token? xxxxxx
What API Host would you like to use? https://api.bigcommerce.com
What port would you like to run the server on? 3000
Set API host to: https://api.bigcommerce.com
You are now ready to go! To start developing, run $ stencil start

### Actual behavior
not ok -- Error: Could not fetch a list of the store channels: Request failed with status code 401

### Steps to reproduce behavior
# Install Chocolatey
iex ((New-Object System.Net.WebClient).DownloadString("https://chocolatey.org/install.ps1"))

# Install git if you don't have it
choco install git

# Install nvm-windows and stencil compatible node.js
choco install nvm; nvm install 12; nvm use 12

#####################################################################################
# Close PowerShell and re-open as admin
#####################################################################################

# Install Windows C++ Build Tools (also installs python2)
npm install -g windows-build-tools --vs2015

# Tell npm to use python2
npm config set python python2.7

# Install Stencil CLI
npm install -g @bigcommerce/stencil-cli

# move into theme dir
cd ~/path/to/theme/dir

# initialize a new .stencil config for the theme
stencil init

# install theme modules
npm install

# serve a live, Browsersync enabled preview of the theme
stencil start

### Environment

Admin Powershell

Stencil-cli version `stencil --version`: 3.1.1 , 3.3.1, 3.1.0

Node version `node -v`: 12.22.12

NPM version `npm -v`: 6.14.16

OS: Windows 11

**Comment by TargetRhino** [comment]
Please help... I'm attempting to use stencil cli on an enterprise store and it is giving me trouble. Thanks in advance!

**Comment by jairo-bc** [comment]
Hi @TargetRhino , do you mind trying latest stencil cli version?

**Comment by TargetRhino** [comment]
I tried and still the same response. I originally thought it was because it was an enterprise account from bigcommerce and there was something blocking the authentication with the multiple stores. I'll welcome any other suggestions

**Comment by jairo-bc** [comment]
@TargetRhino how old is your token?

**Comment by TargetRhino** [comment]
Just tried with a new token. It loaded up for me except for the elements are a little off than what the current theme looks like  and got the following error at the bottom of this text: 
[Browsersync] Proxying: **INFO REMOVED**
[Browsersync] Access URLs:
 -----------------------------------
       Local: **INFO REMOVED**
    External: **INFO REMOVED**
 -----------------------------------
          UI: **INFO REMOVED**
 UI External: **INFO REMOVED**
 -----------------------------------
[Browsersync] Watching files...
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'webpack-merge'
Require stack:
- C:\**INFO REMOVED**\webpack.dev.js
- C:\Users\**INFO REMOVED**\stencil.conf.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\**INFO REMOVED**\webpack.dev.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
**INFO REMOVED**
  ]
}

**Comment by jairo-bc** [comment]
@TargetRhino The error you are seeing `Error: Cannot find module 'webpack-merge'`, it's a theme problem, you might haven't run `npm install` on it. 
If the issue, still occurs (after running `npm install`), I would recommend you to contact theme maintainers.

**Comment by nicolaslule** [comment]
Getting a new API token fixed my issue (I am using Stencil CLI version 4).
