### ISSUE TITLE
not ok -- StoreHashReadError: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by zachadams16** [bigcommerce/stencil-cli#916]
### Expected behavior
When I run stencil start the store is supposed to load as it was yesterday. 

### Actual behavior
Today it is giving me the error not ok -- StoreHashReadError: Client network socket disconnected before secure TLS connection was established
### Steps to reproduce behavior
stencil start or stencil pull

**Comment by acwo** [comment]
I encountered the same problem. Until half an hour ago everything was ok, suddenly it broke my connection with bigcommerce and I cannot connect again, as above.

**Comment by yarovojigor1988** [comment]
I have the same problem.

**Comment by zachadams16** [comment]
So probably a problem with them right now?

**Comment by zachadams16** [comment]
Sounds good thanks. At least not something on my end

**Comment by Tonyaap** [comment]
Same here!

**Comment by zachadams16** [comment]
should be fixed now. working for me
