### ISSUE TITLE
Installation Failure Referencing git://github.com/bigcommerce-labs/node-sass.git

### ISSUE THREAD

**Issue by htokuda10** [bigcommerce/stencil-cli#943]
### Expected behavior
Installation to occur without failure.

### Actual behavior
Installation fails to connect to github.com.

**Log**
- npm sill pacote Retrying git command: ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git attempt # 2
- npm sill pacote Retrying git command: ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git attempt # 3
- npm sill fetchPackageMetaData error for @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0 Error while executing:
- npm sill fetchPackageMetaData /usr/bin/git ls-remote -h -t git://github.com/bigcommerce-labs/node-sass.git
- npm sill fetchPackageMetaData 
- npm sill fetchPackageMetaData fatal: unable to connect to github.com:
- npm sill fetchPackageMetaData github.com[0: 140.82.112.3]: errno=Operation timed out
- npm sill fetchPackageMetaData 
- npm sill fetchPackageMetaData 
- npm sill fetchPackageMetaData exited with error code: 128

**Note**
I noticed that a push was made 10 days ago that included a major version bump to `simple-git`. Not sure if that could be contributing to this issue. 

### Steps to reproduce behavior
Clean install of `npm install -g @bigcommerce/stencil-cli@3.5.1`.

### Environment
macOS Monterey - Version 12.2
NPM Version - 6.14.16
Node Versions tried - 10.24.1, 12.22.10, 14.19.1

**Comment by jairo-bc** [comment]
Hi @htokuda10, I would suggest you to update stencil cli version, since that one has older git protocol, that is not support anymore by GitHub.

**Comment by htokuda10** [comment]
@jairo-bc I removed the version specificity and the install completed successfully. Thank you.
