### ISSUE TITLE
Feature Request: Hosted Docker Image 

### ISSUE THREAD

**Issue by AdamJHall** [bigcommerce/stencil-cli#948]
With the latest release (5.0) a new Dockerfile was added for stencil but this has to be built by the user. This means they have to clone the repository, run a build and then use the image. I was hoping it would be possible for BC to set up an automated build on docker hub so that this wouldn't be needed.

**Comment by bookernath** [comment]
Great idea! Will discuss it with the team.

**Comment by jairo-bc** [comment]
https://github.com/bigcommerce/stencil-cli#running-in-docker
